### ISSUE TITLE
Bug when chaining versioned tasks?

### ISSUE THREAD

**Issue by kstamatiou** [DigitalGlobe/gbdxtools#100]
This works:

location = 's3://gbd-customer-data/58600248-2927-4523-b44b-5fec3d278c09/platform-stories/trial-runs/test/10400100238BDE00/'
rename1 = gbdx.Task('gdal-cli') 
rename1.inputs.data = location
rename1.inputs.execution_strategy = 'runonce'
rename1.inputs.command = """mv $indir/*.tif $outdir/kostas.tif"""
rename2 = gbdx.Task('gdal-cli') 
rename2.inputs.data = rename1.outputs.data.value
rename2.inputs.execution_strategy = 'runonce'
rename2.inputs.command = """mv $indir/*.tif $outdir/kostasthebarbarian.tif"""
wf = gbdx.Workflow([rename1, rename2])
wf.savedata(rename2.outputs.data, 'platform-stories/trial-runs/test2')
wf.execute()

However, this does not work:

location = 's3://gbd-customer-data/58600248-2927-4523-b44b-5fec3d278c09/platform-stories/trial-runs/test/10400100238BDE00/'
rename1 = gbdx.Task('gdal-cli:0.0.1') 
rename1.inputs.data = location
rename1.inputs.execution_strategy = 'runonce'
rename1.inputs.command = """mv $indir/*.tif $outdir/kostas.tif"""
rename2 = gbdx.Task('gdal-cli') 
rename2.inputs.data = rename1.outputs.data.value
rename2.inputs.execution_strategy = 'runonce'
rename2.inputs.command = """mv $indir/*.tif $outdir/kostasthebarbarian.tif"""
wf = gbdx.Workflow([rename1, rename2])
wf.savedata(rename2.outputs.data, 'platform-stories/trial-runs/test2')
wf.execute()

The returned error is:

GBDX API Status Code: 400
GBDX API Response: {"status": "400 Bad Request", "message": "Workflow validate() failed. Make sure the workflow tasks and ports are consistent."}

**Comment by nricklin** [comment]
I believe this is related to #99

**Comment by nricklin** [comment]
fixed in version 0.11.1
