### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by kstamatiou** [DigitalGlobe/gbdxtools#106]
This example does not work:

https://github.com/DigitalGlobe/gbdxtools/blob/master/examples/Catalog_Image_Example.ipynb

In [12]: from gbdxtools import CatalogImage
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-12-c630b0f1198e> in <module>()
----> 1 from gbdxtools import CatalogImage

ImportError: cannot import name CatalogImage

In [13]:

**Comment by nricklin** [comment]
This is not in pypi yet, only on the master branch.  Is that the issue?

**Comment by kstamatiou** [comment]
Potentially. I haven't tried installing directly from master.
Should we have examples that use code which is not on pypi?

**Comment by nricklin** [comment]
No, but it will eventually go onto pypi after we are happy with installation ease

**Comment by nricklin** [comment]
pushed into pypi.  does it work with latest release?

**Comment by kstamatiou** [comment]
Installed latest version from pypi. No, it does not work.

ImportError                               Traceback (most recent call last)
<ipython-input-5-c630b0f1198e> in <module>()
----> 1 from gbdxtools import CatalogImage

ImportError: cannot import name CatalogImage

**Comment by chelm** [comment]
@kostasthebarbarian in a completely clean conda env i was to `pip install gbdxtools` and then import CatalogImage just fine. 

Can you verify that you're pip install is using v 0.11.5?

**Comment by kstamatiou** [comment]
Seems to be an ipython issue. Fresh install of ipython solved the problem. Closing.
