### ISSUE TITLE
IpeImage load_url helper assumes a fixed block size when handling errors

### ISSUE THREAD

**Issue by pramukta** [DigitalGlobe/gbdxtools#107]
[This line](https://github.com/DigitalGlobe/gbdxtools/blob/master/gbdxtools/images/ipe_image.py#L82) assumes that all blocks are 256x256 when recovering from errors. I'm hoping there might be a better way / maybe a different place to handle this.

**Comment by chelm** [comment]
This also an issue with implementing a Landsat Image class as the block sizes are 512x512. I got around it by passing the block size around a bit more heavy handedly but I bet we can find the correct solution to the landsat case and this issue would also get resolved.

**Comment by pramukta** [comment]
This is fixed in the radd-dev branch.
