### ISSUE TITLE
Write function that returns image chip given cat_id and bounding box.

### ISSUE THREAD

**Issue by nricklin** [DigitalGlobe/gbdxtools#11]
_From @kostasthebarbarian on April 2, 2016 0:49_

Use TMS service (https://github.com/TDG-Platform/idaho/blob/dev/developer_documentation/idaho_design/TMS_Service_API.md)

We need this function for training machine learning algorithms.

_Copied from original issue: kostasthebarbarian/gbdxtools#23_

**Comment by nricklin** [comment]
should probably use the chip service https://github.com/TDG-Platform/idaho/blob/dev/developer_documentation/idaho_design/TMS_Service_API.md#chip
because it gives you a native-rez chip

**Comment by kstamatiou** [comment]
@nricklin, @jeffnaus, @deepscience  

Does this exist? 
I have not been able to figure this out after 20min of looking at the code and the examples which means that there's something wrong.

Here is the functionality we need:

get_chip(catalog_id, box, other_parameters_with_default_values)

I want to enter a catalog_id and a box and get the corresponding tif in my local dir. The remaining parameters should have default values. I don't want to deal with idaho ids, buckets, etc.

Let's be clear on terminology. A chip is the raster contained within the box. It could consist of multiple idaho tiles but the user should not have to worry about this.

So:

def get_idaho_chip(self, bucket_name, idaho_id, center_lat, center_lon, 
                       output_folder, pan_id=None)

does not do what I want.

Also, what is the difference between 

view_idaho_tiles_by_bbox(self, catId, bbox, output_filename)

and 

download_idaho_tiles_by_bbox(self, catId, bbox, resolution, outputfolder)

?

**Comment by kstamatiou** [comment]
Update: We should leverage the new API that the IDAHO team is building to address this issue.
