### ISSUE TITLE
issue with pycurl: ImportError: pycurl: libcurl link-time version (7.37.1) is older than compile-time version (7.43.0)

### ISSUE THREAD

**Issue by nricklin** [DigitalGlobe/gbdxtools#112]
```
>>> from gbdxtools import Interface
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gbdxtools/__init__.py", line 2, in <module>
    from gbdxtools.images.idaho_image import IdahoImage
  File "gbdxtools/images/idaho_image.py", line 3, in <module>
    from gbdxtools.images.ipe_image import IpeImage
  File "gbdxtools/images/ipe_image.py", line 56, in <module>
    import pycurl
  File "build/bdist.macosx-10.10-intel/egg/pycurl.py", line 7, in <module>
  File "build/bdist.macosx-10.10-intel/egg/pycurl.py", line 6, in __bootstrap__
ImportError: pycurl: libcurl link-time version (7.37.1) is older than compile-time version (7.43.0)
```

**Comment by chelm** [comment]
Hey nricklin can you tell me how you installed gbdxtools in this case? I'd like to be able to repro this.

**Comment by chelm** [comment]
Looks like the issue related to pycurl and how it looks for its libs. 

I found this asa a possible solution, but really I need to reproduce it to verify, https://github.com/binux/pyspider/issues/472#issuecomment-273457801

**Comment by nricklin** [comment]
```
pip install -U pip
pip install -U gbdxtools
``` 
in a fresh venv on a mac.

**Comment by kstamatiou** [comment]
I also encountered this. In a conda environment, I solved it by installing pycurl:

conda install pycurl

**Comment by chelm** [comment]
yup ok in clean conda env (not venv) i got a similar error after installing gbdxtools via `pip`. 

`Incompatible library version: pycurl.so requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0`

And of course running `conda install pycurl` then was able to import just fine. So there's something about pip and the system libcurl thats not happy

**Comment by nricklin** [comment]
I've installed homebrew and used that to install curl:  no dice.

I've installed conda per the readme, that's resulting in:
```
➜  ~ conda create -n env python ipython
zsh: command not found: conda
```

**Comment by nricklin** [comment]
alright, needed to
```
source ~/.bash_profile
```
which is where conda install stuck path info.

**Comment by nricklin** [comment]
So I got it working by installing conda, then installing pycurl and gbdxtools in conda.

We should either figure out how to make it work with pip, or tell everybody to use conda.

**Comment by chelm** [comment]
I was able to fix this by: 

```
brew install curl
brew link curl --force
brew install openssl
pip --no-cache-dir install gbdxtools
python -c "from gbdxtools import Interface"
```

But im not 100% on it being the univeral solution. I'm all for using conda personally but I can update the README to help users with pycurl in pip.

**Comment by chelm** [comment]
As per a comment from @pramukta this could be a packaging error in the latest wheel from pycurl. We might be able to pin a version of pycurl that works as expected.

**Comment by nricklin** [comment]
ok i'll close this issue.  There's enough info in this thread to get it working.
