### ISSUE TITLE
Pansharpen operator produces wonky image

### ISSUE THREAD

**Issue by nricklin** [DigitalGlobe/gbdxtools#113]
Following the example from the docs:
```
from gbdxtools import CatalogImage

img = CatalogImage('104001001BA7C400', pansharpen=True, bbox=[2.2889757156372075,48.87067123176554,2.301077842712403,48.87705036103764])
img.plot()
```
produces an image that looks like this:
<img width="1075" alt="screenshot 2017-05-01 09 16 38" src="https://cloud.githubusercontent.com/assets/5749532/25583419/e88b3302-2e4e-11e7-9137-f1a37f3416ae.png">

**Comment by pramukta** [comment]
@nricklin This is due to a bad interaction between the IPE GeospatialMosaic operator and the LocallyProjectivePanSharpen operator. The `radd-necessary-optimizations` branch works around this slightly by reordering the graphs so that the GeospatialMosaic happens at the end, though this is not the solution.  @nmcintyre2014 and @dmccabe-dg are working on the underlying issue starting with fixing the mosaic operator.

**Comment by chelm** [comment]
@pramukta @nricklin should we PR the pansharpen fix that gets around the issues with mosiacing as a small focused PR? i started a branch that pulls in just those changes and creates at least more usable pansharp image.

**Comment by pramukta** [comment]
I dunno, would defer to @nricklin on that one.  Another complication is that I think there may be a (significant?) performance hit as well.  There would also be another PR once @dmmcabe-dg's mosaic fix is deployed.

**Comment by chelm** [comment]
yeah I saw that it adds what I think are a lot of redundant metadata requests for gain settings etc. I think we can reuse the data from one request as the data are derived from the sensor at acq. time not the idaho images themselves. 

Unless you're talking about a perf hit on image fetching from that graph structure?

**Comment by pramukta** [comment]
Those metadata hits are way small in comparison to the IPE metadata hit.
More concerned about the IPE metadata and image fetching performance.

**Comment by nricklin** [comment]
aside from performance, I think adding small incremental PRs that improve functionality and won't break as server-side updates happen is a good idea.

**Comment by pramukta** [comment]
This appears fixed
