### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by jambonrose** [DigitalGlobe/gbdxtools#114]
Hi,
What is your recommended Python setup for Windows?

We've attempted to use `gbdxtools` on Windows 10 via Anaconda 4.3's Python 3.6.  Unfortunately, [this line](https://github.com/DigitalGlobe/gbdxtools/blob/e35e1f4316ef70130c38f86d6491356e7be3ddb4/gbdxtools/images/ipe_image.py#L14) causes an error when importing `gbdxtools` because [Python does not support those signal types on Windows](https://docs.python.org/3.6/library/signal.html#signal.signal).

We're about to try this with Python 3.6 installed via Cygwin, but I am wary of this option because of the difficulty of building/installing scientific packages like SciPy. I'd appreciate any insights you have about running `gbdxtools` on Windows with other scientific tools.

Thanks!

**Comment by jambonrose** [comment]
After installing Python on Cygwin, we are still seeing the same error.

**Comment by chelm** [comment]
Thanks for opening this issue @jambonrose I'll add an exception handler to that line today that will hopefully unblock you from getting it installed.
