### ISSUE TITLE
Write function that creates IDAHO image.

### ISSUE THREAD

**Issue by nricklin** [DigitalGlobe/gbdxtools#12]
_From @kostasthebarbarian on April 2, 2016 0:51_

In case the IDAHO image corresponding to a CATID does not exist, we need to be able to create it.

_Copied from original issue: kostasthebarbarian/gbdxtools#24_

**Comment by nricklin** [comment]
this would look like:
- hit the idaho-ingest API (but it's kinda alpha) that tells you the workflow json
- launch the workflow
- wait

**Comment by kstamatiou** [comment]
Should gbdxtools  deal with this? Ultimately, we want idaho images to be invisible to the user. 
The user cares only about location and catalog id.
