### ISSUE TITLE
Using gbdxtools with staging catalog returns 401

### ISSUE THREAD

**Issue by michaelconnor00** [DigitalGlobe/gbdxtools#120]
When using gbdxtools with the **staging.geobigdata.io** environment, doing a `gbdx.catalog.get('10200100132C5700')` will return:
```
{"status": "401 Unauthorized", "message": "Authentication Failed."}
``` 
It is known that when using catalog V2 or any index in vector services, you need to use a production auth token, even for staging endpoints. So this behaviour may effect more than one component of gbdxtools.

**Comment by chelm** [comment]
Is this a gbdxtools issue or a server auth issue @michaelconnor00 ?

**Comment by michaelconnor00** [comment]
@chelm the explanation I got says vector services can only use production auth tokens. 

gbdxtools (gbdx-auth) gets staging tokens, and I have used it lots with the other endpoints such as running workflows on the staging env. It just breaks when you try to hit the staging catalog.

**Comment by chelm** [comment]
ok thanks @michaelconnor00 im not sure at all how to fix that.

**Comment by nricklin** [comment]
I think your best bet is a personal monkey-patch of some sort.  I don't think we ought to build into gbdxtools the ability to get different auth tokens for different services.

**Comment by michaelconnor00** [comment]
Yeah, that would be easy enough. 

```
from gbdxtools import Interface
prod = Interface(config_file='/path/to/prod_config.ini')
stag = Interface(config_file='/path/to/staging_config.ini', host='staging.geobigdata.io')
metadata = prod.catalog.get('10200100132C5700')
wf = stag.Workflow([stag.Task('MyTask_beta', data=metadata)])
wf.execute()
```

The use case where this is more of a nuisance is with a task's runtime. If a task uses gbdxtools to hit the catalog, the gbdx_runtime.json will have a token from that environment. So if you run that task on staging, you will get a staging token, and trying to hit the catalog will fail. Although, I believe this use case if quite rare. So easiest fix is not to run the task on staging :).

Thanks for the help.

**Comment by pramukta** [comment]
Based on @nricklin's comment looks like this is a wontfix so closing out.
