### ISSUE TITLE
Malformed JSON responses

### ISSUE THREAD

**Issue by Brett55** [DigitalGlobe/gbdxtools#121]
I found multiple places where JSON is returned to the user, but the responses are malformed. Either the responses are not formatted (spacing, indentation) correctly, include 'u' unicode characters, sometimes python dictionaries vs valid JSON, etc

- Get Events
- Get Stdout/Stderr
- Convert workflow to JSON

**Comment by nricklin** [comment]
I think events, stdout, & stderr should be python dictionaries.  I think they currently are, aren't they?

**Comment by Brett55** [comment]
I saw a mix of python dicts, unicode characters, and or unformatted json
responses
