### ISSUE TITLE
Random black tiles on CatalogImage access

### ISSUE THREAD

**Issue by nricklin** [DigitalGlobe/gbdxtools#127]
Running this:
```python
from gbdxtools import CatalogImage

img = CatalogImage('104001001BA7C400', pansharpen=True) 
aoi = img.aoi(bbox=[2.2889757156372075,48.87067123176554,2.301077842712403,48.87705036103764])
aoi.plot(w=10, h=10)
```
Results in random black tiles:
![image](https://user-images.githubusercontent.com/5749532/27393198-dfd9af06-5665-11e7-858f-442003847b6e.png)

**Comment by nricklin** [comment]
Check this out:  similarly i'm seeing intermittent tiles in the wrong places.
<img width="892" alt="screenshot 2017-06-21 11 59 43" src="https://user-images.githubusercontent.com/5749532/27399285-7c39585c-5679-11e7-84a5-6cfebe0402b1.png">

**Comment by chelm** [comment]
still trying to reproduce this one. the black tiles seem to be expected if there are any network issues while communicating with the image servers, but the misplacing of tiles is much more of a mystery.

**Comment by pramukta** [comment]
Closing pending merge, but important to note that our client side fix shouldn't be considered a solution to this issue.
