### ISSUE TITLE
s3.download does not recreate directory structure - it flattens it.

### ISSUE THREAD

**Issue by nricklin** [DigitalGlobe/gbdxtools#13]
_From @kostasthebarbarian on April 2, 2016 13:7_

Let's have this function recreate the directory structure.

_Copied from original issue: kostasthebarbarian/gbdxtools#25_

**Comment by nricklin** [comment]
Here's a snippet that we use in gbdx to do this.  

https://gist.github.com/nricklin/86df62d99c48c9623ed616ed9b568eab

**Comment by nricklin** [comment]
@naldeborgh7575  Is this issue resolved with your recent PR?

**Comment by nricklin** [comment]
#67

**Comment by naldeborgh7575** [comment]
Yes

**Comment by kstamatiou** [comment]
Done!
