### ISSUE TITLE
unable to import rasterio.io 

### ISSUE THREAD

**Issue by lababidi** [DigitalGlobe/gbdxtools#132]
I'm attempting to `import gbdx` but this breaks due to `from rasterio.io import MemoryFile` in the `ipe.py` file within gbdx. The following error is thrown.
`No module named 'rasterio.io'`

**Comment by chelm** [comment]
@lababidi Can you detail the steps you took to install gbdxtools? Rasterio >= v1.0a3 is required and should be installed when installing via pip.

**Comment by lababidi** [comment]
That was the key. `pip install rasterio==1.0a9` was what it took. I'm not sure if I can try to reproduce this issue, but it was installing v0.36 consistently.
