### ISSUE TITLE
Error downloading processed images

### ISSUE THREAD

**Issue by ivanhigueram** [DigitalGlobe/gbdxtools#135]
Good day, 

I am tying to process (`AOP_Strip_Processor`) some images issuing a simple workflow using the following code: 

```python

#Order images function (Loop/Map over the images and do fancy things)

def proccesing_gbdx(img_id, wkt):
    #Order imagery
    order = gbdx.Task("Auto_Ordering", cat_id=img_id)
    order.impersonation_allowed = True
    
    #Preprocess imagery - DRA + Pansharpening + AComp + Ortho
    aop_multispectral = gbdx.Task('AOP_Strip_Processor',
                                  data=order.outputs.s3_location.value,
                                  bands='PAN',
                                  enable_dra=False,
                                  enable_pansharpen=False,
                                  enable_acomp=True,
                                  ortho_epsg='EPSG:4326',
                                  dra_mode ='BaseLayerMatch'
                                 )

    #Crop only to points buffer bbox
    crop = gbdx.Task('CropGeotiff',
                    data=aop_multispectral.outputs.data.value, 
                    wkt_0=wkt, wkt_1=wkt)
    
    #Start workflow and define variables (in S3)
    wf = gbdx.Workflow([order, aop_multispectral, crop])
    wf.savedata(crop.outputs.data_0, location="folder-under-prefix-s3")
    wf.execute()
    return wf


results = processing_gbdx(<some catalog ID>, <some WKT POLYGON>)
```
Nonetheless, the `'AOP_Strip_Processor'` task is failing when I specify the option ` bands='PAN'`. The metadata on the images confirms that the images are panchromatic only and I was hoping to process them completely, but the process is failing. 

Do you know what I am doing wrong? 

[I attached the printout of events of the workflow]

Thanks for your help. 

[workflow_events.txt](https://github.com/DigitalGlobe/gbdxtools/files/1115387/workflow_events.txt)

**Comment by chelm** [comment]
hi @ivanhigueram i'll pull down your code and see if I can reproduce what you're seeing but I did just notice a typo in your code above... 

your function name is `proccesing_gbdx` but you are calling `processing_gbdx` that might have been just a copy and paste error though.

**Comment by chelm** [comment]
@ivanhigueram I was able to run your code successfully. Can you send me a CatalogID and WKT that you've used and seen fail?

**Comment by ivanhigueram** [comment]
Oops! Sorry for the late answer. I have already sent an email with the issue by the GBDX client support. The images I was trying to download and pre-process only had one band (PAN). Hence, the `'AOP_Strip_Processor'` Task was failing since this pre-process is designed to multi-band/multispectral imagery. It was my mistake!

Thank you so much for your prompt answer.
