### ISSUE TITLE
Workflow.status() looks for `state` and not `status`

### ISSUE THREAD

**Issue by lababidi** [DigitalGlobe/gbdxtools#137]
`Workflow.status()` is looking for `return r.json()['state']` within the response. `state` doesn't exist in the following response I caught by debugging: `'{"status": "404 Not Found", "message": "Not Found"}`

**Comment by Brett55** [comment]
@lababidi can you show more of your code to see how workflow was initialized

**Comment by lababidi** [comment]
@Brett55 it wouldn't help. This is just the case for a 404, where I sent the wrong workflow_id. 

the issue is that there's no `state` in the response. either GBDX API needs to fix that, or look for `status` in the gbdxtools.

**Comment by pramukta** [comment]
Addressed somewhat in a the new release (0.13.4).
