### ISSUE TITLE
getting 404 on CatalogImage and IdahoImage

### ISSUE THREAD

**Issue by willcadell** [DigitalGlobe/gbdxtools#152]
Hello!

I'm getting a 

> BadRequest: Problem fetching image metadata: status 404 /

from 

`nd_array = IdahoImage('5940c85d-9743-4269-a2c4-c5e69ebb35ae')`

and

`nd_array = CatalogImage('103001006CCF6100')`

(which point at the same resource)

I'm using the gbdxtools available from pypi (0.13.1). What have I got wrong?

Thanks!

**Comment by willcadell** [comment]
just upgraded to 0.13.3, still same experience :(

**Comment by willcadell** [comment]
full trace back from CatalogImage:

---------------------------------------------------------------------------
BadRequest                                Traceback (most recent call last)
<ipython-input-22-28420d467495> in <module>()
----> 1 nd_array = CatalogImage('103001006CCF6100')

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/catalog_image.py in __new__(cls, cat_id, **kwargs)
     33     '''
     34     def __new__(cls, cat_id, **kwargs):
---> 35         return cls._image_by_type(cat_id, **kwargs)
     36 
     37     @classmethod

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/catalog_image.py in _image_by_type(cls, cat_id, **kwargs)
     45             raise Exception('Could not find a catalog entry for the given id: {}'.format(cat_id))
     46         else:
---> 47             return cls._image_class(cat_id, result[0], **kwargs)
     48 
     49     @classmethod

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/catalog_image.py in _image_class(cls, cat_id, rec, **kwargs)
     51         types = rec['properties']['item_type']
     52         if 'WV02' in types:
---> 53             return WV02(cat_id, **kwargs)
     54         elif 'WV03_VNIR' in types:
     55             return WV03_VNIR(cat_id, **kwargs)

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/worldview.py in __new__(cls, cat_id, **kwargs)
    116 class WV02(WVImage):
    117     def __new__(cls, cat_id, **kwargs):
--> 118         return super(WV02, cls).__new__(cls, cat_id, **kwargs)

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/worldview.py in __new__(cls, cat_id, **kwargs)
     50 
     51         try:
---> 52             self = super(WVImage, cls).__new__(cls, standard_products[options["product"]])
     53         except KeyError as e:
     54             print(e)

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/ipe_image.py in __new__(cls, op)
     21     def __new__(cls, op):
     22         assert isinstance(op, DaskMeta)
---> 23         self = super(IpeImage, cls).create(op)
     24         self._ipe_op = op
     25         if self.ipe.metadata["georef"] is None:

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/meta.py in create(cls, dm)
    123         assert isinstance(dm, DaskMeta), "argument must be an instance of a DaskMeta subclass"
    124         with dask.set_options(array_plugins=[dm.infect]):
--> 125             obj = da.Array.__new__(cls, dm.dask, dm.name, dm.chunks, dm.dtype, dm.shape)
    126             return obj
    127 

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/ipe/interface.py in dask(self)
    161     def dask(self):
    162         token = self._interface.gbdx_connection.access_token
--> 163         _chunks = self.chunks
    164         _name = self.name
    165         img_md = self.metadata["image"]

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/ipe/interface.py in chunks(self)
    173     @property
    174     def chunks(self):
--> 175         img_md = self.metadata["image"]
    176         return (img_md["numBands"], img_md["tileYSize"], img_md["tileXSize"])
    177 

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/ipe/interface.py in metadata(self)
    151     @property
    152     def metadata(self):
--> 153         assert self.graph() is not None
    154         if self._ipe_meta is not None:
    155             return self._ipe_meta

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/ipe/interface.py in graph(self, conn)
    144             self._ipe_id = register_ipe_graph(conn, graph)
    145             self._ipe_graph = graph
--> 146             self._ipe_meta = get_ipe_metadata(conn, self._ipe_id, self._id)
    147             return self._ipe_graph
    148 

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/ipe/graph.py in get_ipe_metadata(conn, ipe_id, node)
     37     md_response = conn.get(VIRTUAL_IPE_URL + "/metadata/{}/{}/metadata.json".format(ipe_id, node)).result()
     38     if md_response.status_code != 200:
---> 39         raise BadRequest("Problem fetching image metadata: status {} / {}".format(md_response.status_code, md_response.reason))
     40     else:
     41         md_json = md_response.json()

BadRequest: Problem fetching image metadata: status 404 /

**Comment by ealpert1** [comment]
This is not a catalog V2 problem. The following works no problem:


https://geobigdata.io/catalog/v2/record/103001006CCF6100 

returns:

{
    "identifier": "103001006CCF6100",
    "type": [
        "GBDXCatalogRecord",
        "Acquisition",
        "DigitalGlobeAcquisition",
        "WV02"
    ],
    "properties": {
        "offNadirAngle_min": 12.693902,
        "offNadirAngle_start": 14.332682,
        "targetAzimuth_min": 25.618738,
        "multiResolution_min": 1.9408412,
        "cloudCover": 1,
        "sunAzimuth_max": 131.6388,
        "targetAzimuth": 31.549204,
        "multiResolution": 1.9515998,
        "catalogID": "103001006CCF6100",
        "panResolution_max": 0.49045163,
        "timestamp": "2017-07-23T18:55:02.000Z",
        "sunAzimuth_min": 129.48239,
        "browseURL": "https://geobigdata.io/thumbnails/v1/browse/103001006CCF6100.large.png",
        "targetAzimuth_max": 37.394585,
        "sunAzimuth": 130.524,
        "sunElevation_min": 69.539185,
        "offNadirAngle": 13.428898,
        "stereoPair": null,
        "platformName": "WORLDVIEW02",
        "multiResolution_start": 1.9653492,
        "sunElevation": 69.929,
        "vendor": "DigitalGlobe",
        "scanDirection": "Forward",
        "panResolution_end": 0.48446038,
        "panResolution_start": 0.49045163,
        "targetAzimuth_end": 37.394585,
        "panResolution_min": 0.48446038,
        "offNadirAngle_max": 14.332682,
        "multiResolution_end": 1.9408412,
        "multiResolution_max": 1.9653492,
        "sunElevation_max": 70.281075,
        "offNadirAngle_end": 12.693902,
        "panResolution": 0.48705074,
        "footprintWkt": "MULTIPOLYGON(((-118.3536814 34.74413602, -118.166337 34.74938844, -118.1664323 34.70469922, -118.166576 34.65998534, -118.1667454 34.61526841, -118.1669609 34.5705327, -118.167649 34.52516538, -118.1670981 34.48159342, -118.1673143 34.43699362, -118.1682067 34.39151142, -118.1682696 34.34719283, -118.1672705 34.30431511, -118.167497 34.25986414, -118.1668984 34.21649597, -118.1665737 34.17279098, -118.1665255 34.12874866, -118.1664367 34.0847975, -118.1664043 34.04082444, -118.1663599 33.99687074, -118.1663924 33.95285774, -118.166416 33.90890032, -118.1664434 33.86495478, -118.1664815 33.82102741, -118.1665146 33.77714459, -118.1665365 33.73330345, -118.1665865 33.68946945, -118.1665902 33.6863451, -118.3509518 33.68151108, -118.3509558 33.68471292, -118.351051 33.7284807, -118.3513986 33.77197411, -118.3511781 33.81620407, -118.3512634 33.8601, -118.3513214 33.90406127, -118.3514138 33.94799853, -118.3515866 33.99187263, -118.3515586 34.03605377, -118.3516785 34.08004137, -118.352075 34.12368336, -118.3519775 34.16808159, -118.3521203 34.21214488, -118.3523324 34.25612879, -118.352539 34.30015941, -118.3530545 34.34373467, -118.3535483 34.38738999, -118.3530177 34.43273309, -118.3532102 34.47692397, -118.353313 34.52131378, -118.3541597 34.56445838, -118.3540689 34.60924419, -118.3539282 34.65417761, -118.3536257 34.69945505, -118.3536814 34.74413602)))",
        "targetAzimuth_start": 25.618738,
        "imageBands": "PAN_MS1_MS2",
        "sensorPlatformName": "WORLDVIEW02"
    }
}

**Comment by pramukta** [comment]
@willcadell Is it still happening for you?  The traceback makes it look like the IPE metadata lookup is failing somehow but I was able to instantiate both images listed above just now (though on Python 2.7).  I'll try to replicate on 3.5 with gbdxtools installed via pypi.

**Comment by pramukta** [comment]
@willcadell I was able to replicate your error.  Looking into it now.

**Comment by pramukta** [comment]
Okay @willcadell, the issue was that we were calling `.content` on a response from the requests library.  In Python 2.7 that was fine since bytes and strings are the same.  Not so much in Python 3.  I just changed this to use `.text` in commit b8b26d8b294b8eaaf97093ab4cf04890704fdfa6 so it should be fixed next time we push a package (which I'm anticipating to be tomorrow or Tuesday at the latest).  I'll post something here when that happens.  In the mean time Python 2.7 should work.  Thanks for reporting this, def keep the issues coming.

**Comment by pramukta** [comment]
wanted to give you a quick update we're running a little behind on cutting the release, working on merging #156 today, and anticipate the release just after.

**Comment by willcadell** [comment]
Thanks! I pipped from the master branch for now, works like a dream, thanks!

**Comment by pramukta** [comment]
Cool, everything is in a new pypi release now (0.13.4).  There's also a conda release installable via:
```
conda install -c digitalglobe gbdxtools
```
however, we're still working on getting the conda package to install on py3.x.  The pip package works fine for now, as does conda for 2.7.  Should be a little bit easier to get binary dependencies working with that.
