### ISSUE TITLE
Bad Request on CatalogImage: Problem registering graph {"error":"Unable to execute HTTP request: Timeout waiting for connection from pool"}

### ISSUE THREAD

**Issue by willcadell** [DigitalGlobe/gbdxtools#153]
Hello there!

I have a process which calls CatalogImage() numerous times. It is calling the same image with different bounding boxes making little chips of the big image.

It runs 19 times fine, on the 20th (of say 50 or so...), i get:

---------------------------------------------------------------------------
BadRequest                                Traceback (most recent call last)
<ipython-input-25-b41b020c10a0> in <module>()
     69                             bboxes.append(json_bbox)
     70                             bbox=[lngMin,latMin,lngMax,latMax]
---> 71                             img = CatalogImage(catID, bbox=bbox, proj='EPSG:4326', pansharpen=True, band_type='MS')
     72                             outname = catID + "-" + key + '.tif'
     73                             tif_img = img.geotiff(path='../data/ships/' + outname, proj="EPSG:4326")

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/catalog_image.py in __new__(cls, cat_id, **kwargs)
     33     '''
     34     def __new__(cls, cat_id, **kwargs):
---> 35         return cls._image_by_type(cat_id, **kwargs)
     36 
     37     @classmethod

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/catalog_image.py in _image_by_type(cls, cat_id, **kwargs)
     45             raise Exception('Could not find a catalog entry for the given id: {}'.format(cat_id))
     46         else:
---> 47             return cls._image_class(cat_id, result[0], **kwargs)
     48 
     49     @classmethod

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/catalog_image.py in _image_class(cls, cat_id, rec, **kwargs)
     51         types = rec['properties']['item_type']
     52         if 'WV02' in types:
---> 53             return WV02(cat_id, **kwargs)
     54         elif 'WV03_VNIR' in types:
     55             return WV03_VNIR(cat_id, **kwargs)

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/worldview.py in __new__(cls, cat_id, **kwargs)
    116 class WV02(WVImage):
    117     def __new__(cls, cat_id, **kwargs):
--> 118         return super(WV02, cls).__new__(cls, cat_id, **kwargs)

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/worldview.py in __new__(cls, cat_id, **kwargs)
     50 
     51         try:
---> 52             self = super(WVImage, cls).__new__(cls, standard_products[options["product"]])
     53         except KeyError as e:
     54             print(e)

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/ipe_image.py in __new__(cls, op)
     21     def __new__(cls, op):
     22         assert isinstance(op, DaskMeta)
---> 23         self = super(IpeImage, cls).create(op)
     24         self._ipe_op = op
     25         if self.ipe.metadata["georef"] is None:

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/images/meta.py in create(cls, dm)
    123         assert isinstance(dm, DaskMeta), "argument must be an instance of a DaskMeta subclass"
    124         with dask.set_options(array_plugins=[dm.infect]):
--> 125             obj = da.Array.__new__(cls, dm.dask, dm.name, dm.chunks, dm.dtype, dm.shape)
    126             return obj
    127 

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/ipe/interface.py in dask(self)
    161     def dask(self):
    162         token = self._interface.gbdx_connection.access_token
--> 163         _chunks = self.chunks
    164         _name = self.name
    165         img_md = self.metadata["image"]

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/ipe/interface.py in chunks(self)
    173     @property
    174     def chunks(self):
--> 175         img_md = self.metadata["image"]
    176         return (img_md["numBands"], img_md["tileYSize"], img_md["tileXSize"])
    177 

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/ipe/interface.py in metadata(self)
    151     @property
    152     def metadata(self):
--> 153         assert self.graph() is not None
    154         if self._ipe_meta is not None:
    155             return self._ipe_meta

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/ipe/interface.py in graph(self, conn)
    142 
    143         if conn is not None:
--> 144             self._ipe_id = register_ipe_graph(conn, graph)
    145             self._ipe_graph = graph
    146             self._ipe_meta = get_ipe_metadata(conn, self._ipe_id, self._id)

/anaconda/envs/GDAL/lib/python3.5/site-packages/gbdxtools/ipe/graph.py in register_ipe_graph(conn, ipe_graph)
     30         return res.text
     31     else:
---> 32         raise BadRequest("Problem registering graph: {}".format(res.text))
     33 
     34 

BadRequest: Problem registering graph: {"error":"Unable to execute HTTP request: Timeout waiting for connection from pool"}

**Comment by pramukta** [comment]
@willcadell, yeah we've been seeing these a bunch and they are unfortunately server side.  Folks on that team are aware and digging into that.  We're also bundling in some retry logic with the next package to make it work more.  You also may try instantiating the `CatalogImage` once and calling the `.aoi` method on it a bunch of times.  This avoids hitting server side request each time and should complete much quicker.  You can pass `bbox`, `geojson`, or `wkt` keys to the `.aoi` method just as you would in the constructor.  Alternatively you can pass a shapely geometry via bracket notation like so `image[g]` (where g is a shapely geometry) and it should do the same thing.
