### ISSUE TITLE
New tempfile based `load_url` method leaks file descriptors

### ISSUE THREAD

**Issue by pramukta** [DigitalGlobe/gbdxtools#154]
Something about the new new `load_url` implementation leaks file descriptors.  The result is that after a period of usage python reports an `OSErr` complaining about too many open files.  The amount will vary by system and settings, but observed this on linux running stock ubuntu.  Unfortunate thing is that the implementation uses a with block so it could be a temporary thing until the garbage collector runs or it could be lack of cleanup after errors / retries or something else.  Unclear.  But definitely exists.

**Comment by pramukta** [comment]
This can't be exactly right.  I'm only seeing this with `GeoImage.warp`

**Comment by pramukta** [comment]
Okay this isn't specifically related to `load_url`, though just for safety will add an explicit close for the tempfile.  What happens is that in situations like warp we create implicit nested calls to `.compute(get=threaded_get)` on dask.Array.  when that involves load_url (and `GBDX_THREADS` is high) this means we open `GBDX_THREADS^2` file descriptors.  Once this happens and throws an error, it doesn't look like fds get cleaned up (but not 100% on that).

**Comment by nricklin** [comment]
gnar.

**Comment by pramukta** [comment]
Closing pending merge.
