### ISSUE TITLE
Strange TMSImage Extents on certain zooms

### ISSUE THREAD

**Issue by chelm** [DigitalGlobe/gbdxtools#161]
When looking at a certain region at different zoom levels i noticed that we are getting some funky extents at zoom levels 17 and 18.

```
from gbdxtools import TmsImage

token = "YOUR KEY"

bbox = [-105.00444889068605, 39.75299710099606, -104.9962091445923, 39.75431683540881]

for z in xrange(13, 20):
    tms = TmsImage(access_token=token, zoom=z)
    aoi = tms.aoi(bbox=bbox)
    print 'zoom', z
    aoi.plot()
```

<img width="345" alt="tms_image" src="https://user-images.githubusercontent.com/351164/30339398-225e2ed8-97ac-11e7-88b7-9a3b08e02247.png">

**Comment by chelm** [comment]
also related it seems that passing bounds to the tms image constructor is resulting in images that are 256x256 in size.

**Comment by chelm** [comment]
i've made a change to the code that removes support for the `bounds` keyword and replaces its with our standard set of geometry types: bbox, geojson, or wkt. The issue previously was that TmsMeta was expecting bounds to be in EPSG:3857. So we could have projected them, but this interface is now much more similar to other image classes

**Comment by pramukta** [comment]
@chelm does that fix the issue? I would expect that if we get the 256x256 issue is fixed the positioning issue will be as well.

**Comment by chelm** [comment]
I would have thought so too, but the 256x256 being fixed unfortunately does not change the extent problem we see here. This issue may be a corner case though, I have been unsuccessful in reproducing it in other locations. It may be that we need to better understand the particular relationship between this extent and the fetched tiles.

**Comment by pramukta** [comment]
Ah ok.
