### ISSUE TITLE
After warp, number of reported tiles in .read/.plot are wrong

### ISSUE THREAD

**Issue by pramukta** [DigitalGlobe/gbdxtools#162]
Possibly happens after other things as well.

**Comment by chelm** [comment]
@pramukta do you have an sample cat id and boox that shows the issue? The number of tiles to fetch are stored in the `ntiles` prop, maybe there's a bug in this calc: 

```python
size = float(self.ipe.metadata['image']['tileXSize'])
return math.ceil((float(self.shape[-1]) / size)) * math.ceil(float(self.shape[1]) / size)
```

**Comment by pramukta** [comment]
@chelm I think the calc is fine, just that once we warp those numbers don't correspond anymore maybe.  I'll paste an example next time it comes up but not crucial anyway.

**Comment by chelm** [comment]
ahh that makes sense

**Comment by drwelby** [comment]
removing warp due too many issues in 8cb0de9fd18bd5ea1df8c03acbf2ca79c48b0449
