### ISSUE TITLE
Error extracting Intel Comiler Library in v 0.13.4

### ISSUE THREAD

**Issue by loominator1970** [DigitalGlobe/gbdxtools#167]
The GBDX customer is having problems when upgrading between v 0.13.3 to 0.13.4.  The issue seems to be be that it fails when extracting the Intel Compiler Library.

I have recommended to the customer to downgrade to ver 0.13.1 while the development team attempts to find the fix (suggested by Chris).  We are also waiting for more error information from the customer.

Dave Loomis

**Comment by pramukta** [comment]
Hmm okay, definitely let me know what the error and (docker/pip?) environment are.  gbdxtools definitely doesn't require the intel compiler, but maybe when it's available maybe some pip installs try and use it which complicates things.  Also happy to interface with the customer directly, if that will help.

**Comment by chelm** [comment]
@loominator1970 can you try having the customer upgrade to the latest gbdxtools v0.13.5? And either report back errors or close this ticket?

**Comment by pramukta** [comment]
I think this issue is resolved or different than identified here, so closing.  Please feel free to reopen (or open a new issue) if there's additional trouble the customer is having.
