### ISSUE TITLE
Create functionality to get WorldView 1 image chips

### ISSUE THREAD

**Issue by kkoperskidg** [DigitalGlobe/gbdxtools#169]
A client that we are working with on a ship identification project needs WorldView 1 image chips

**Comment by chelm** [comment]
@kkoperskidg I just pushed support for WV01 imagery via `CatalogImage`:

```python
from gbdxtools import CatalogImage
img = CatalogImage('1020010044CEA300')
a = img.randwindow((500,500))
a.plot()
```
