### ISSUE TITLE
gbdx.search.catalog does not work with filters

### ISSUE THREAD

**Issue by ms280690** [DigitalGlobe/gbdxtools#170]
gbdxtools==0.13.4
Used gbdx.search.catalog returns no results but using the same request in postman and using the requests library works and returns results.
```
gbdx.catalog.search(startDate="2017-09-17T00:00:00.000Z",
                              endDate="2018-09-17T23:59:59.999Z",
                              filters=["bucketName = 'bucket_name'",
                                       "bucketPrefix = 'bucket_prefix'"]
                              )
```

Results are returned without the `filter`.

**Comment by chelm** [comment]
@ms280690 Thanks for the issue, using other filters i was able to get results so i'm wondering if its related to the `bucketName` and `bucketPrefix` filters. Can you share the bucketName and bucketPrefix you're using?

**Comment by ms280690** [comment]
@chelm 
```
[
"bucketName = 'receiving-dgcs-tdgplatform-com'",
"bucketPrefix = '057019011010_01_003/057019011010_01/057019011010_01_P002_PAN'"
]
```

**Comment by ealpert1** [comment]
Is it possible you record does not exist? I just ran the following and it worked fine

{  

    "filters":[
"bucketName = 'receiving-dgcs-tdgplatform-com'",
"bucketPrefix = 055754190010_01_003/055754190010_01/055754190010_01_P003_PAN"

]
}

**Comment by ms280690** [comment]
@ealpert1 
```
[
"bucketName = 'receiving-dgcs-tdgplatform-com'",
 "bucketPrefix = '055032439020_01_003/055032439020_01/055032439020_01_P002_PAN'"
]
```
Returns an empty list using `gbdxtools` but through postman returns results.
Any thoughts?

**Comment by ms280690** [comment]
```
{
	"startDate": "2017-09-17T00:00:00.000Z",
	"endDate": "2018-09-17T23:59:59.999Z",
	 "filters": ["bucketName = 'receiving-dgcs-tdgplatform-com'", "bucketPrefix = '057019313010_01_003/057019313010_01/057019313010_01_P003_MUL'"]
}
```
Trying it out at https://gbdxdocs.digitalglobe.com/docs/catalog-v2-search-by-filters and postman returns identical results. But,
```
gbdx.catalog.search(startDate="2017-09-17T00:00:00.000Z",
                              endDate="2018-09-17T23:59:59.999Z",
                              filters=["bucketName = 'receiving-dgcs-tdgplatform-com'",
                                       "bucketPrefix = '057019313010_01_003/057019313010_01/057019313010_01_P003_MUL'"])
```
Returns an empty list.

**Comment by chelm** [comment]
This has to do with the setting of `Types` in the catalog.search method. By default we're searching for `Acquisition` types and you can override this by passing `types=["GBDXCatalogRecord"]` to the search method.

**Comment by chelm** [comment]
@ms280690 going to close this issue

**Comment by chelm** [comment]
Though I do think we should change the default behavior and default types to None
