### ISSUE TITLE
Task timeout maximum is too low

### ISSUE THREAD

**Issue by mjgleason** [DigitalGlobe/gbdxtools#175]
The maximum allowable timeout for a task via gbdxtools is too low. It is currently set to a maximum of 40,000 seconds (~11 hrs)
 (https://github.com/DigitalGlobe/gbdxtools/blob/0707695f8a620b46d318267dec96605f41a03420/gbdxtools/simpleworkflows.py#L311), but the actual GBDX task limit is 172,800 seconds (48 hrs).

**Comment by pramukta** [comment]
@mjgleason updated in development, will go into the next merge

**Comment by mjgleason** [comment]
Thanks @pramukta
