### ISSUE TITLE
Add workflow search feature

### ISSUE THREAD

**Issue by mjgleason** [DigitalGlobe/gbdxtools#177]
The GBDX API includes a POST request that allows you to search for all workflows run by a given user over a given lookback period (in hours). The base URL is https://geobigdata.io/workflows/v1/workflows/search, and the body of the post request include the following json:

```json
{
    "lookback_h":12,
    "owner":"someuser@somedomain.com"
}
``` 

The API returns a list of workflow IDs. It would be nice to have access to this feature in gbdxtools.

**Comment by chelm** [comment]
@mjgleason this has been pushed to the `dev` branch. It might be a couple weeks before a new tagged release is made though, but it's in. 

```python
from gbdxtools import Interface
gbdx = Interface()
gbdx.workflow.search(lookback_h=200, state='all')
```

**Comment by mjgleason** [comment]
awesome, thanks @chelm
