### ISSUE TITLE
GeoDaskWrapper cant be indexed via geometries

### ISSUE THREAD

**Issue by chelm** [DigitalGlobe/gbdxtools#179]
The indexing of images from GeoDaskWrapper seems to missing the proper geometry handling done in `__getitem__` 

```python
from gbdxtools.images.meta import GeoDaskWrapper
import dask.array as da
import numpy as np

dsm = np.ones((256,256))

wat = da.from_array(dsm.astype(np.float32), chunks=(256,256))
a = {
    "dask": dict(wat.dask),
    "name": wat.name,
    "chunks": wat.chunks,
    "dtype": wat.dtype,
    "shape":wat.shape
}

from gbdxtools import CatalogImage

catalog_id = '104001002895C400'
image = CatalogImage(catalog_id)
ref = image[:, 0:256, 0:256]

img = GeoDaskWrapper(a, ref)

from shapely.geometry import shape
img[shape(image)]
```

**Comment by chelm** [comment]
`TypeError: ('Invalid index type', <class 'shapely.geometry.polygon.Polygon'>, <shapely.geometry.polygon.Polygon object at 0x11b9725d0>)`

**Comment by pramukta** [comment]
I've seen this before, and used a workaround (which I have now forgotten).  Will look into it when back in Denver.

**Comment by chelm** [comment]
fixed by adding the getitem from ipe image with a couple small changes for GeoDaskWrappers
