### ISSUE TITLE
AssertionErrorTraceback on CatalogImage for catid 104001002D01DB00

### ISSUE THREAD

**Issue by mjgleason** [DigitalGlobe/gbdxtools#183]
I'm getting an AssertionError with the following code. 
```python
nc_catid = '104001002D01DB00'
nc_bounds = (35.9251, -75.6215, 35.9366, -75.6053)
nc_aoi = CatalogImage(nc_catid).aoi(bbox=nc_bounds)
nc_aoi.plot(w=15, h=15)
```

Any idea what's going on here?

**Comment by mjgleason** [comment]
Nevermind, it works if I flip the lat/long ordering. In the sample above, I pulled the bbox coords directly out of the GBDX Notebooks imagery tab, so it might make sense to flip the ordering in the imagery tab to match what the bbox argument expects.

**Comment by chelm** [comment]
@mjgleason yeah that issue in the notebook UI has been resolved, sorry about that.
