### ISSUE TITLE
Incorrect size chips returned

### ISSUE THREAD

**Issue by kkoperskidg** [DigitalGlobe/gbdxtools#188]
img = CatalogImage('1030010051094900', band_type="MS", acomp=False, proj="epsg:32732", gsd=2.0, product="ortho")
selection = img.aoi(wkt='POLYGON ((5.42269961078 59.7229927685,5.44398037984 59.7229927685,5.44398037984 59.7122213848,5.42269961078 59.7122213848,5.42269961078 59.7229927685))') # reads 9 tiles
data = selection.read()
selection = img.aoi(wkt='POLYGON ((5.30285313392 60.0411594709,5.32436352795 60.0411594709,5.32436352795 60.0303886776,5.30285313392 60.0303886776,5.30285313392 60.0411594709))') # reads 714 tiles
data = selection.read()

Both polygons are approximately same size, second intersects image (part of polygon is outside image)
For the second polygon chip has the height of image.

**Comment by chelm** [comment]
This could be an error/bug in the reporting. I'll check to see if its actually reading that many tiles or not.

**Comment by chelm** [comment]
The shapes being reported here make me think it def not a bug in reporting but elsewhere: 

The first AOI is (8, 632, 631)
The second AOI is (8, 60775, 632)

So that means 714 is in thoery correct, the next question is why is it returning such a tall array?

**Comment by chelm** [comment]
This is pointing me towards a bug with our zero padding of AOIs that are not completely contained by an image. The second is at the edge of the image. 

```python
from shapely.wkt import loads

aoi2 = loads('POLYGON ((5.30285313392 60.0411594709,5.32436352795 60.0411594709,5.32436352795 60.0303886776,5.30285313392 60.0303886776,5.30285313392 60.0411594709))')
aoi1 = loads('POLYGON ((5.42269961078 59.7229927685,5.44398037984 59.7229927685,5.44398037984 59.7122213848,5.42269961078 59.7122213848,5.42269961078 59.7229927685))')

print shape(img).contains(aoi1) 
#> True
print shape(img).contains(aoi2)
#> False
```

**Comment by chelm** [comment]
this is all taken care of
