### ISSUE TITLE
Cleanup actions

### ISSUE THREAD

**Issue by kstamatiou** [DigitalGlobe/gbdxtools#19]
- Create DG pypi account for new repo and delete the one for kostasthebarbarian

**Comment by kstamatiou** [comment]
I haven't been able to find any information on whether removing gbdxtools from kostasthebarbarian pypi account allows us to upload a new gbdxtools package under the DG account.

**Comment by nricklin** [comment]
let's practice with a test package

**Comment by kstamatiou** [comment]
Do we still need this? You have been able to push to pypi, right?

**Comment by nricklin** [comment]
I have not been able to push yet

**Comment by kstamatiou** [comment]
Simplest solution is to manually add owners with push rights to pypi. Closing
