### ISSUE TITLE
Workflow status attributes do not cover all cases

### ISSUE THREAD

**Issue by duckontheweb** [DigitalGlobe/gbdxtools#192]
We have some code that checks on the status of a workflow using the attributes documented [here](http://gbdxtools.readthedocs.io/en/latest/running_workflows.html#workflow-status)(`workflow.succeeded`, `workflow.failed`, etc.). However, there appear to be workflow status cases that are not covered by the attributes alone, so we end up needing to mix using the attributes with checks on `workflow.status['event']` in order to cover all possible cases:

```python
if workflow.succeeded:
    ...
elif workflow.failed or workflow.canceled:
    ...
elif workflow.timedout:
    ...
elif workflow.running or workflow.status['event'] in ['submitted', 'scheduled']:
    ...
else:
    log.error('Could not find workflow status')
```

I would prefer to be able to do this entirely via the attribute-based checks, so maybe adding something like `workflow.pending` and/or `workflow.submitted` would be helpful.

Thanks!

**Comment by chelm** [comment]
@duckontheweb seems like it'd be straight forward enough to add properties to the workflow class that gives you what you're looking for. I'm not too familiar with that specific code but can look into where it might fit, would you be interested in co-crafting a pr for that?

**Comment by duckontheweb** [comment]
Yeah, I'd love to. I'll get familiar with that part of the code and get in touch with some ideas.

**Comment by duckontheweb** [comment]
It looks like this should be a simple matter of adding some read-only properties to the `Workflow` class in `simpleworkflows.py` using some of the [other status attributes](https://github.com/DigitalGlobe/gbdxtools/blob/master/gbdxtools/simpleworkflows.py#L629-L639) as a guide. 

The `state` cases that I've seen so far have been:

```json
{
    "state": "pending",
    "event": "scheduled"
}
```

and

```json
{
    "state": "pending",
    "event": "submitted"
}
```

but it's possible there are others we want to catch as well.

**Comment by duckontheweb** [comment]
Alright, looks like we can get the unique combinations of `state` and `event` from the class attributes on `PrimaryState` and `Event` [here](https://github.com/TDG-Platform/workers_and_deciders/blob/master/workers_and_deciders/components/state.py#L9-L31). @chelm Maybe we can put our heads together tomorrow or Monday to figure out how we want to handle the various cases.

**Comment by duckontheweb** [comment]
... and [here](https://github.com/TDG-Platform/workers_and_deciders/blob/master/workers_and_deciders/components/workflow.py#L359-L422) is the logic that takes the status of the individual tasks in a workflow and translates that into a single workflow-level `state`/`event` combo.

I'll dig into this and come up with some ideas on how to handle the various combos.

**Comment by duckontheweb** [comment]
Here's the logic tree for parsing a workflow state based on it's component task states based on the core code referenced above:

```
If any task.state.event == ...
    |
    | - 'failed'
    |     | - state = 'complete'
    |     | - event = 'failed'
    |
    | - 'timedout'
    |     | - state = 'complete'
    |     | - event = 'timedout'
    |
    | - 'canceling'
    |     | - state = 'running'
    |     | - event = 'canceling'
    |
    | - 'canceled'
    |     | - state = 'complete'
    |     | - event = 'canceled'
    |
    | - 'started'
    |     | - state = 'running'
    |     | - event = 'started'
    |
    | - 'scheduled'
    |     | - If any task.state.event == 'succeeded'...
    |     |     | - state = 'running'
    |     |     | - event = 'scheduled'
    |     |
    |     | - Otherwise...
    |     |     | - state = 'pending'
    |     |     | - event = 'scheduled'
    |   
    | - 'rescheduling'
    |     | - If any task.state.event == 'succeeded'...
    |     |     | - state = 'running'
    |     |     | - event = 'rescheduling'
    |     |
    |     | - Otherwise...
    |     |     | - state = 'pending'
    |     |     | - event = 'rescheduling'
    |
    | - 'waiting'
    |     | - If any task.state.event == 'succeeded'...
    |     |     | - state = 'running'
    |     |     | - event = 'waiting'
    |     |
    |     | - Otherwise...
    |     |     | - state = 'pending'
    |     |     | - event = 'waiting'
    |
    | - 'submitted'
    |     | - If any task.state.event == 'succeeded'...
    |     |     | - state = 'running'
    |     |     | - event = 'submitted'
    |     |
    |     | - Otherwise...
    |     |     | - state = 'pending'
    |     |     | - event = 'submitted'
    |  
...else if all task.state.events == 'succeeded'...
          | - state = 'complete'
          | - event = 'succeeded'
...otherwise...
          | - ERROR
```

**Comment by chelm** [comment]
Nice

**Comment by duckontheweb** [comment]
@chelm What do you think about the following schema for status attributes? The `complete` and `running` attributes are complementary and basically just tell you whether the workflow is still churning or not. The rest have more specific information on that success/status of the workflow. This should cover all possible combinations (except for an API error).

### Running State

#### Existing Attributes

* `complete`: Workflow is done running.
    * `event: failed`, `state: complete`
    * `event: succeeded`, `state: complete`
    * `event: timedout`, `state: complete`

* `running`:  Workflow is still churning.
    * all event/state combos not caught by `complete`

#### New Attributes

* None

### Success State

#### Existing Attributes

* `succeeded`: All workflow tasks succeeded.
    * `event: succeeded`, `state: complete`

* `timedout`: At least one workflow task timed out.
    * `event: timedout`, `state: complete`

* `failed`: At least one workflow task failed.
    * `event: failed`, `state: complete`

* `canceled`: Workflow was canceled.
    * `event: canceled`, `state: complete`

#### New Attributes

* `scheduling`: Workflow task is being scheduled.
    * `event: scheduled`, `state: running`
    * `event: scheduled`, `state: pending`

* `rescheduling`: Workflow task is being rescheduled.
    * `event: rescheduling`, `state: running`
    * `event: rescheduling`, `state: pending`

* `waiting`: Workflow is waiting.
    * `event: waiting`, `state: running`
    * `event: waiting`, `state: pending`

* `submitting`: Workflow is being submitted.
    * `event: submitted`, `state: pending`
    * `event: submitted`, `state: running`

**Comment by chelm** [comment]
Looks solid to me @duckontheweb

**Comment by duckontheweb** [comment]
Sounds good. I'll put together a PR with these changes and flag you when it's ready for some eyes.

**Comment by duckontheweb** [comment]
Actually, @jsplitt would you mind taking a look at the logic tree above just to make sure I'm not missing anything?

**Comment by chelm** [comment]
Believe we got this PR'd last week, closing

**Comment by duckontheweb** [comment]
@chelm Looks like I missed one case when I put this PR in:

```python
status == {
    'event': 'submitted',
    'state': 'running'
}
```

I'm wondering if it would make the most sense to have the `running` property just return `False` if the workflow `state` is `"succeeded"`, `"failed"`, or `"timedout"`, and `True` for everything else. That seems to be the logic for [batch workflows checks](https://github.com/DigitalGlobe/gbdxtools/blob/master/gbdxtools/simpleworkflows.py#L649-L652), but not for [individual workflow checks](https://github.com/DigitalGlobe/gbdxtools/blob/master/gbdxtools/simpleworkflows.py#L654). 

I can put in a PR for this if you'd like, or if it's just easier for you to make a change that works, too.

**Comment by duckontheweb** [comment]
And actually, the `{'event': 'submitted', 'state': 'pending'}` case isn't getting caught either. Maybe I'll take another look at this and put in a PR to correct my mistakes.

**Comment by chelm** [comment]
@duckontheweb Awesome, if you can put together a PR that'd be wonderful. It might be a couple weeks before i can look at this closely enough.

**Comment by duckontheweb** [comment]
No worries, it's not a big rush. I built a workaround into our codebase for the time-being.
