### ISSUE TITLE
workflow.timedout attribute not documented

### ISSUE THREAD

**Issue by duckontheweb** [DigitalGlobe/gbdxtools#193]
The `workflow.timedout` attribute is not documented alongside the other workflow status checks [here](http://gbdxtools.readthedocs.io/en/latest/running_workflows.html#workflow-status) and it would be nice to have that in the same place.

Thanks!

**Comment by chelm** [comment]
Simple enough to add here: https://github.com/DigitalGlobe/gbdxtools/blob/master/docs/running_workflows.rst

Are there other events that need to be added?

**Comment by duckontheweb** [comment]
@chelm I would be happy to add a PR for this once we've finished work on #192. We'll probably have a more complete list at that point.
