### ISSUE TITLE
Invalid GDAL URL in Troubleshooting Docs

### ISSUE THREAD

**Issue by duckontheweb** [DigitalGlobe/gbdxtools#194]
The raw GitHub URL for GDAL seems to be invalid in the README [here](https://github.com/DigitalGlobe/gbdxtools#troubleshooting) (returns 404). 

Changing to this url fixes the problem: `https://raw.githubusercontent.com/OSGeo/homebrew-osgeo4mac/master/Formula/gdal2.rb`.

I can put in a quick PR for this if desired.

**Comment by chelm** [comment]
no need, i just updated it

**Comment by chelm** [comment]
thanks!

**Comment by duckontheweb** [comment]
Awesome, thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
