### ISSUE TITLE
rasterio dependency is troublesome

### ISSUE THREAD

**Issue by colllin** [DigitalGlobe/gbdxtools#196]
I've never seen it install cleanly.  Tried on ubuntu and macOS.  What is it used for?  Can we split it out into a different/separate module, or make it a softer dependency?  I've only needed the S3 and workflow API capabilities of gbdxtools in these instances, and the difficulty of installing rasterio makes gbdxtools utterly useless for this purpose.  It's easier to make the API calls manually than figure out how to install rasterio.

I'll contribute changes/fixes if you can guide me in the right direction.

**Comment by chelm** [comment]
@colllin How are you trying to install rasterio, and how are you installing gbdxtools?

**Comment by chelm** [comment]
We've talked about making it an optional dep, we use it for creating geotiffs from images really quickly and in a couple other places since it has some handy methods, but those are replaceable with a little bit of work.

**Comment by chelm** [comment]
ping @colllin - any other info here? code? errors?

**Comment by nricklin** [comment]
Can you try "conda install -c digitalglobe gbdxtools" ?

This should work everywhere.  We could make this more clear in the readme.

**Comment by colllin** [comment]
Is it easy to run conda within a virtualenv? I haven’t done that before.   
  

  
We ended up not using GBDX for the project I was working on, so I don’t have anything to add or update from the original issue.   
  

  
  

  
  
>

**Comment by colllin** [comment]
What’s the reason for closing?  Gbdxtools now requires conda?
