### ISSUE TITLE
CatalogID, ordering confusion

### ISSUE THREAD

**Issue by matthewhanson** [DigitalGlobe/gbdxtools#200]
I've been using gbdxtools to query the catalog and create GeoJSONs containing the footprints and metadata. I then want to get access to the underlying data, but I'm at a bit of a loss as to how to actually do this.

If I use the catalogID as is illustrated in the documentation
```
img = CatalogImage('103001000F8FC000')
# i get
Exception: Could not find a catalog entry for the given id: 103001000F8FC000
```

Ok, so then I thought maybe I have to order this data first, so after ordering and waiting for an s3 location I try:

```
img = CatalogImage('104A010010C29F00')
# and get
    raise UnsupportedImageType('Unsupported image type: {}'.format(str(types)))
gbdxtools.ipe.error.UnsupportedImageType: Unsupported image type: ['GBDXCatalogRecord', 'WV03_SWIR', 'DigitalGlobeProduct', '1BProduct']
```

Ok, so this is a WV03 image, so I thought I might need WV03_VNIR class instead of CatalogImage, but this particular case is the SWIR bands.

I also tried to just access the S3 data location, but the documentation is unfortunately pretty vague on that count too. I can list stuff in my own s3 prefix as given by the s3 creds I get from the GBDX API, but the location of ordered imagery is in another bucket entirely, and one that I can't list the contents of. And there's no functionality in gbdxtools that I can see that simplifies the downloading of the scenes.

Any pointers here would be greatly appreciated!

**Comment by chelm** [comment]
Hey @matthewhanson - Sorry for the confusion. I'd like to clear this up for sure, gbdxtools could probably do users a favor and have better explanations for various errors, I'll give myself that task. 

In the meantime i'll try my best to explain:

`Exception: Could not find a catalog entry for the given id: 103001000F8FC000` you're assumption here is correct, that image has got to be ordered. Ordering will move that ID from an `Acquisition` to a `Product`.

Re WV03_SWIR - I don't think we've got support for the the SWIR data yet, but this is something i can look it today/this week and add. Apologies. 

With regard to accessing the s3 bucket directly you wont permissions to access the primary s3 bucket/prefix, but only those in your s3 location. Though gbdxtools does provide an image class for accessing data from s3 directly via the `S3Image` class, it wont work for us here unfortunately. There's got to be something we can do to get that image into your bucket. I'll look into that this morning.

**Comment by chelm** [comment]
@matthewhanson I just added WV03 SWIR support to gbdxtools (on the dev branch). We might be able to get a build/release out this week, but in the meantime you could pull the dev branch if its urgent. 

See commit 091ef106666cae8310f42e497f17659fc5eb2ff3

**Comment by chelm** [comment]
I'll take a pass at better error messages this week, but also let me know if there's anything else you'd like clarified or added to the docs. I can make that happen.

**Comment by matthewhanson** [comment]
Thanks a lot @chelm !  I'm able to order and fetch scenes, and working on figuring out workflows.
