### ISSUE TITLE
Projection parameter to geotiff does not warp image

### ISSUE THREAD

**Issue by matthewhanson** [DigitalGlobe/gbdxtools#203]
I'm using the geotiff function to save an area of an image.

When I call CatalogImage.geotiff without supplying the proj keyword I get a Coordinate system in the resulting file:

 ```
Size is 1421, 1087
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (36.961150386230685,-1.457843223460294)
Pixel Size = (0.000018145885735,-0.000018145885735)
```

If I instead provide a projection string such as EPSG:32737 I get:
```
Size is 1421, 1087
PROJCS["WGS 84 / UTM zone 37S",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",39],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",10000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","32737"]]
Origin = (36.961150386230685,-1.457843223460294)
Pixel Size = (0.000018145885735,-0.000018145885735)
```

The spatial reference system has been update but the geotransform parameters have not as can be seen from the Origin and Pixel Size which are still in lat/lon, not meters, and the number of pixels is the same in both images so it has not been warped.

**Comment by chelm** [comment]
@matthewhanson interesting, will look into it right now and see whats up.

**Comment by chelm** [comment]
@matthewhanson i see the issue, not handling the warp. Will need some time to solve how best to do this in a chunked fashion, but i think we have a strategy for doing it. 

You're best bet for now would be to let the server handle the reprojection by passing  `proj="EPSG:32737"` to the CatalogImage constructor.

Sound good?

**Comment by matthewhanson** [comment]
Thanks @chelm I'll give that a try, or I can reproject client side too.

BTW, gippy has fewer dependencies as rasterio (really it's just GDAL), and has a convenient method for doing that reprojection utilizing the GDAL chunking and warping API.  I've been starting to look into Dask for gippy, it already does image chunking automatically, and stores function chains for deferred operation, but Dask offers up some more possibilities.

**Comment by chelm** [comment]
@matthewhanson also rasterio has been giving some users trouble on installation, but i think those troubles are more related to gdal installation issues than any other deps. There a few places we use rasterio for fetching/reading tifs from the server and some window/transform functions, but both of those can easily be replaced with a few lines of code. 

The only place we really rely on it is in the `geotiff` method, but it sucks that I missed the need for client side reprojection in that method. 

We do have a client warping method called `.warp` that can take a proj string, dem, etc and reproject/transform/warp, and it works well in that it leverages our use Dask nicely. The transformations are all deferred so we can essentially transform an entire strip and then only compute when we need to fetch data. 

I looked at gippy and looks nice. Will dig in some more

**Comment by matthewhanson** [comment]
@chelm Sorry this is a bit off-topic here, but I'm unclear on the difference between the IDAHO tiles and Catalog imagery. Is the catalog imagery all non-orthorectified? If I want orthorectified imagery I should use IDAHO and/or create a workflow and use the Advanced Image Preprocessor. Is that correct?

Also, is there any way to combine CatalogImages and Workflows? Can you run an image through a Workflow and open/crop it as a CatalogImage?

**Comment by chelm** [comment]
Hey @matthewhanson so its a bit of deep question and I'll try to shed some light. So historically we've stored imagery as 1b, non-ortho'd data. IDAHO is a just a data format that virtually represents that data as tiles+metadata. The IDAHO format is typically passed through a processing graph that does things like ortho etc. 

Typically in workflows users would run a workflow/task such a the AOP task and they'd get a giant tiff in s3 that was ortho/acompd/pansharpened. But that task doesnt leverage IDAHO or any gbdxtools image interfaces at all. It operates on entire strips, where gbdxtools/CatalogImage lets us work with imagery in smaller chunks, tile-by-tile.

So in gbdxtools' CatalogImage we actaully use IDAHO tiles that have been ortho'd. So it's a bit deceiving. 

So the answer to whether or not its possible to use CatalogImages in workflows is dependent on how the task is written. Most tasks at this point dont use the new gbdxtools interfaces but instead operate on the entire raw strip. This is changing as we create more tasks built off gbdxtools. 

Does that help @matthewhanson?  it is a bit confusing, but its a product of the changing data access we're currently developing.

**Comment by matthewhanson** [comment]
Yes, this was super helpful @chelm thanks a lot.

What I was getting at here was that I had some small regions I wanted to run some GBDX tasks on,  so I was hoping to be able to do a crop followed by some task.  What we ended up doing was using CatalogImages - cropping then fetching the data and running our own algorithms outside of the GBDX platform. So it was very useful to know that these CatalogImgaes actually go through the IDAHO process (does this happen on-the-fly?) to get ortho'd (and DRA'd and pansharpened if desired).

However, I'm now doing a traditional workflow with the 'CropGeotiff' followed by 'AOP_Strip_Processor', which seems to work (although getting an algorithm to work after that is variable - the deep core car finder algorithm has messed up geolocation information if pre-cropping, but if you don't pre-crop it works, but its terribly inefficient and expensive computing-wise since I don't need to run it on the whole strip.

**Comment by chelm** [comment]
@matthewhanson This is great feedback. Our goal is to get most tasks capable of working with catalog images for the exact reasons you've run into: "terribly inefficient and expensive computing-wise". 

An advanced user of the platform could make catalog images work. For instance could create a task that inits a catalog image, crops it to AOI and dumps out a tif on s3. Then that task in theory could be fed to the car counter and other algorithms. But like you said if there are issues with geo location post crop, that doesn't help much. 

Thanks for taking the time to follow up

**Comment by matthewhanson** [comment]
@chelm Happy to provide feedback, I could provide more having dived into GBDX this past month, but I think this has veered far enough from "Projection parameter to geotiff does not warp image". I'm particularly interested in hearing more details about the ortho/atmcorr/dra process using the IDAHO pipeline.

I'll be publishing an open-source repo or two in the next few weeks that helps make the discovery and fetching of clipped catalog imagery easier. It's nothing you can't do with gbdxtools, it's just a command line tool (using gbdxtools) that's a bit more turnkey, and does so by building upon the functionality of [sat-search](https://github.com/sat-utils/sat-search), so allows saving search results as geojson, loading those later, etc....stay tuned.

**Comment by chelm** [comment]
going to close this issue as the solution for projections currently is to init an image with a projection and let the server project it. 

@matthewhanson if you want to hear more about the IDAHO pipeline for ortho etc just hit me up.
