### ISSUE TITLE
Pinning of jpeg==8d prevents install of gbdxtools with latest opencv via conda

### ISSUE THREAD

**Issue by pramukta** [DigitalGlobe/gbdxtools#210]
As it says above, the error is about unsatisfiable dependencies.  This is on mac under python 2.7.

**Comment by chelm** [comment]
ok, i cant remember exactly why we pinned to 8d it was the result of a day of dep trouble, but will look again.

**Comment by pramukta** [comment]
It was because of a broken jpeg package, forget which one

**Comment by chelm** [comment]
with changes to dev yesterday i believe that pinning jpeg to 8d is no longer needed. Just test locally and will push to dev

**Comment by chelm** [comment]
new version, 0.14.1 removes pinning jpeg
