### ISSUE TITLE
Installing gbdxtools via conda on windows fails with unsatisfiable dependencies

### ISSUE THREAD

**Issue by pramukta** [DigitalGlobe/gbdxtools#211]
Don't know what's going on here, it there is a chance it is a local environment thing but installing gbdxtools by itself in a new conda environment on windows using python 2.7 or 3.5 fails with errors about unsatisfiable dependencies, and no indication of what dependencies it's talking about.

**Comment by chelm** [comment]
interesting i think mikesmith just confirmed it worked for him on windows

**Comment by pramukta** [comment]
I wonder if there are differences between windows 7 and 10.  Will dig more
when I get home.

**Comment by rjpolackwich** [comment]
weird, I had issues installing gbdxtools when rebuilding some docker images recently. was inheriting from an image that had previously installed rasterio. installing gbdxtools failed with unsatisfiable dependencies: libspatialite. removing the rasterio install in the parent image fixed it... not sure why, fwiw thought id' mention it

**Comment by chelm** [comment]
he did try windows 10, not sure about 7

**Comment by chelm** [comment]
not clear what to do about this

**Comment by pramukta** [comment]
Okay I have a little more information.  I suspect it may be relate to the root anaconda distribution being a python 3.6 one by default.  It looks like despite the particular environment having python 2.7 or 3.5, conda still believes something is 3.6 (like maybe the interpreter it's executing under).

**Comment by chelm** [comment]
ok great, so this is related to the known 3.6 dep bug. So maybe if we can pinpoint that dep there and address it this will go away. And... we really need to support 3.6 anyway.

**Comment by pramukta** [comment]
yeah true, and I bet this same thing happens on mac/linux as well, so not specifically a windows thing

**Comment by pramukta** [comment]
mmm no luck could be a red herring.

**Comment by chelm** [comment]
yeah me too, was actually able to install latest in py3.6 no problem

**Comment by chelm** [comment]
Going to close this one. If other windows users report a similar issue on the latest releases I'll dig deeper.
