### ISSUE TITLE
accessing RADARSAT-2 data

### ISSUE THREAD

**Issue by joemcglinchy** [DigitalGlobe/gbdxtools#218]
Hello, I was wondering if it is possible to access RADARSAT-2 data from the gbdxtools API? I see it can be returned from the search API using Postman. I checked out one of the entries (below) and tried both the 'Identifier' and 'CatalogID' as arguments to CatalogImage. I get the following errors:

CatalogImage('PDS_05854100') 
``` Exception: Could not find a catalog entry for the given id: PDS_05854100 ```

CatalogImage('556282')
```UnsupportedImageType: Unsupported image type: [u'GBDXCatalogRecord', u'RADARSAT2', u'SGFProduct', u'MDAProduct']```

Does this mean RADARSAT-2 data can't yet be accessed with CatalogImage or something similar, and is limited to task-workflow execution only?

```{
            "identifier": "PDS_05854100",
            "type": [
                "GBDXCatalogRecord",
                "RADARSAT2",
                "SGFProduct",
                "MDAProduct"
            ],
            "properties": {
                "beamMode": "Extra Fine",
                "lutApplied": "Point Target",
                "processingTime": "2017-05-15T05:30:14.000000Z",
                "metadataFiles": [
                    "product.xml"
                ],
                "productID": "PDS_05854100",
                "timestamp": "2017-05-02T00:06:55.484Z",
                "catalogID": "556282",
                "imageFiles": [
                    "imagery_HH.tif"
                ],
                "passDirection": "Descending",
                "platformName": "RADARSAT-2",
                "polarizations": [
                    "HH"
                ],
                "vendor": "MacDonald, Dettwiler and Associates Ltd.",
                "lutFiles": [
                    "lutBeta.xml",
                    "lutSigma.xml",
                    "lutGamma.xml"
                ],
                "beams": "XF0W2",
                "bucketPrefix": "73630002fd302b4d7b15155d65917b822ffc69a031e31982b063f36eff3d60a079cb363495b64304306497101178559e347b4104dec9bcaef27e55fa6a819c85598fd0c8c094693cdd8374b1c41af5592828341da1702092354dc65cba2fe28647eb95f0f5dba9bc4d8a2f8f5d897b85cc2b3d0be84143453b65206613e3",
                "incidenceAngleNearRange": 31.6551342,
                "bucketName": "73630002ff1d6756d009eebc8852b8a36d21f0f9ef30e6b4a11566693eb8af78693f15fba9bfaf42ea2938fddb8dd3919ba06cf1159f1ae128a994ea99c97d12adfa3f482226702d99d96baaea491bbaed62082c7e1737b54bc96f",
                "productLevel": "SGF",
                "incidenceAngleFarRange": 38.8319855,
                "processingFacility": "GSS",
                "footprintWkt": "MULTIPOLYGON(((89.2437182298 41.1499502397, 89.538701227 42.3803113875, 91.009766403 42.1773245873, 90.6859592147 40.9469875805, 89.2437182298 41.1499502397)))",
                "softwareVersion": "CAPPS SAR 1.3",
                "sensorPlatformName": "RADARSAT-2",
                "lookDirection": "Right"
            }
        }
```

**Comment by chelm** [comment]
Let me dig into this a little bit and I'll let you know what can be done. Currently Radarsat is not accessible via gbdxtools, but i think the general attitude at DG is that it should be. However, there is one little hurdle and thats that the bucketname and prefix to the data living in S3 are encrypted and need to be decrypted in order to fetch the pixels. I've decrypted them with a key in the past but i'm pretty sure the thinking is that the key shouldn't become publicly accessible.  

I'll figure out if we can get support decrypting them on the server, and if so I can add Radarsat to gbdxtools.

**Comment by chelm** [comment]
Got some info back on this and unfortunately we're not going to have support for Radarsat for some time still. There are a number of blockers that prevent us from efficiently providing any sort of meaningful access to the Radarsat archive. As those barriers are removed i'll work on getting what ever support we can provide into gbdxtools.
