### ISSUE TITLE
sentinel 2 data (1/2): where are 20m and 60m bands?

### ISSUE THREAD

**Issue by joemcglinchy** [DigitalGlobe/gbdxtools#220]
Hello,

I was looking at using Sentinel-2 image data with gbdxtools. I notice that the image that comes back is 4 band, and after digging further, saw the specification for the 10 meter bands for a Sentinel2 image. I was wondering if it is possible to get the 20m and 60m bands by specifying some parameter, or if it hasn't been supported yet?

-Joe

**Comment by chelm** [comment]
I need to look at the data/docs, and verify we can access the other bands, but i believe that it just wasnt implemented on the first release of sentinel support. I am confident that we can get it supported soon.

**Comment by joemcglinchy** [comment]
thanks Chris! I will keep an eye out for future support of the 20m and 60m products.

**Comment by chelm** [comment]
@joemcglinchy i knew this issue had sounded familiar, but basically I just need to add docs for Sentinel 2 data (will take care of that). We currently support 10m, 20m and 60m already. In the image constructor just specify the resolutions as the `spec` property (one of 10, 20, or 60 meters): 

`Sentinel2(..., spec="10m|20m|60m") `

**Comment by joemcglinchy** [comment]
sweet. I verified this with the AOI code and verified the dimensions are different. Thanks!
