### ISSUE TITLE
gbdxtools task_registry is hiding Errors

### ISSUE THREAD

**Issue by lababidi** [DigitalGlobe/gbdxtools#224]
when you run
`print(gbdx.task_registry.register(json_filename='task-description-singleshot.json'))`
and there's some error, the only thing returned is
`HTTPError: 400 Client Error: Bad Request for url: https://geobigdata.io/workflows/v1/tasks`

This obfuscates the real error and leaves the user confused on what needs to be done.

**Comment by chelm** [comment]
This must be the default behavior in requests' `raise_for_status()` method. I'll try to capture the actual error returned by the server and see if i can throw it.

**Comment by chelm** [comment]
Yeah we can augment the way it responds and have it raise with the server message like so: 

`RequestException: {"status": "400 Bad Request", "message": "WORKFLOW API: Schema validation failed: u'name' is a required property"} `

**Comment by chelm** [comment]
closing. pushed a fix to master that will be included in the next release
