### ISSUE TITLE
CatalogImage(id) not available, but returns a result in API search via Postman

### ISSUE THREAD

**Issue by joemcglinchy** [DigitalGlobe/gbdxtools#226]
I saw that a Catalog ID which I can get metadata for in Postman via a GET command:

https://geobigdata.io/catalog/v2/record/1040010036874500

however, when trying to access that same catalog ID via CatalogImage('1040010036874500') I receive this error. 

```
Could not find a catalog entry for the given id: 1040010036874500
```

I'm just wondering if there is not a 1:1 between what you might get from the ordering/search API and what is directly available through dask? would I need to order the image first and then use an S3Image class? Or is there a better way to get around that?

**Comment by chelm** [comment]
That ID is listed as a `DigitalGlobeAcquisition` which means its not ordered yet. Once its ordered then a new record in the catalog gets created as a `DigitalGlobeProduct`. Once its been delivered you'll be able to use to the CatalogImage class on it. No need to use an s3image. 

I think i'll change that error message to include something about ordering the catalog id first.

**Comment by joemcglinchy** [comment]
ok, so in that case it would be necessary to use the AutoOrder task, wait for it to be delivered, and then use the same CatalogImage(ID) call?

**Comment by chelm** [comment]
Yes exactly.

**Comment by joemcglinchy** [comment]
I tried this and checked the workflow status, it all checks out. But, I still cannot access the image with CatalogImage:

```

        try:

            img = CatalogImage(dg_catid)
            print('DG image was ready right away')

        # IF THIS FAILS, it means the scene needs to be ordered.
        except:
            print('DG image needs to be ordered')
            gbdx = Interface()

            tasks = []
            output_location = 'auto_orders/task'

            # Pre-Image Auto ordering task parameters
            pre_order = gbdx.Task("Auto_Ordering")
            pre_order.inputs.cat_id = dg_catid
            pre_order.impersonation_allowed = True
            pre_order.persist = True
            pre_order.timeout = 36000
            tasks += [pre_order]

            workflow = gbdx.Workflow(tasks)
            
            # Execute workflow
            workflow.execute()

            while workflow.status['event'] != "succeeded":
                if workflow.status['event'] == "failed":
                    print('GBDX image ordering failed for some reason')
                else:
                    time.sleep(2)
                    pass

            # order the image
            img = CatalogImage(dg_catid)
```

The final call to CatalogImage(dg_catid) produces this error:

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-28-e58b773ffe13> in <module>()
     73 
     74             # order the image
---> 75             img = CatalogImage(dg_catid)
     76             print('DG image has been ordered and can be accessed')
     77 

C:\Anaconda2\envs\gbdxtool_updates\lib\site-packages\gbdxtools\images\catalog_image.pyc in __new__(cls, cat_id, **kwargs)
     34     '''
     35     def __new__(cls, cat_id, **kwargs):
---> 36         return cls._image_by_type(cat_id, **kwargs)
     37 
     38     @classmethod

C:\Anaconda2\envs\gbdxtool_updates\lib\site-packages\gbdxtools\images\catalog_image.pyc in _image_by_type(cls, cat_id, **kwargs)
     44         result = vectors.query(aoi, query=query, count=1)
     45         if len(result) == 0:
---> 46             raise Exception('Could not find a catalog entry for the given id: {}'.format(cat_id))
     47         else:
     48             return cls._image_class(cat_id, result[0], **kwargs)

Exception: Could not find a catalog entry for the given id: 1040010036874500
```

even though the workflow.status['event'] shows up as succeeded:

```
workflow.status
{u'event': u'succeeded', u'state': u'complete'}
```

I then tried to order it with the ordering api:
```
            # order the scene
            order_id = gbdx.ordering.order(dg_catid)
            print (str(order_id))

            # The order_id is unique to your image order and can be used to track the progress of your order. The ordered image sits in a directory on S3. The output of the following describes where:
            status = gbdx.ordering.status(order_id)
            print('scene ' + id + ' has been ordered, waiting for delivery...')

            # Make sure DRA is disabled if you are processing both the PAN+MS files
            #Edit the following line(s) to reflect specific folder(s) for the output file (example location provided)
            # data = str(status[0]['location'])

            while 's3' not in str(gbdx.ordering.status(order_id)[0]['location']):
                time.sleep(2)
                pass
            
            # get the image
            img = CatalogImage(dg_catid) 
```

however, I receive the same error. Here is the information I see for ```gbdx.ordering.status(order_id)[0]```:

```
{u'acquisition_id': u'1040010036874500',
 u'location': u's3://receiving-dgcs-tdgplatform-com/057274924010_01_003',
 u'state': u'delivered'}
```

It seems it is delivered. I'm not sure why I can't then access it via CatalogImage with that id?

**Comment by chelm** [comment]
There is a lag in the system. Should have mentioned this. Once the system has delivered the image from the factory it kicks off some ingest processes and even though it says delivered, its not quite ready to work with gbdxtools just yet. The timing can be a slow if there are alot of orders happening. 

This is something we're working to address.

**Comment by chelm** [comment]
@joemcglinchy so my only advice is that it will appear, and hopefully soon

**Comment by joemcglinchy** [comment]
ok cool, good to know!

**Comment by joemcglinchy** [comment]
I'd like to re-open this... it has been ~3 weeks and this item is still not available via CatalogImage requests.

```
"type": [
        "GBDXCatalogRecord",
        "Acquisition",
        "DigitalGlobeAcquisition",
        "WV03_VNIR"
    ]
```

CatalogImage('1040010036874500') still gives me the `Exception: Could not find a catalog entry for the given id: 1040010036874500` error. I am looking in another area now, too, and I get this error for 33 out of 39 of the scenes I am interested in analyzing. What is the best way to get around this??

**Comment by chelm** [comment]
This is strange. I have verified that the order completes successfully but no DGProduct is created for the catalog id. Will look into it.

**Comment by chelm** [comment]
@joemcglinchy Ok this particular catalog id has been fixed, but there may be others in the catalog with similar integrity issues. What we need to do our own end is find them and correct them (and of course prevent them from ever appearing). 

Do want to share the list of 39 ids you mentioned and i can run a quick test to see if any of them are impacted?

**Comment by joemcglinchy** [comment]
@chelm sure here are the IDs

[u'103001000390AF00',
 u'1030010056565000',
 u'103005004AF92E00',
 u'103001002CB22C00',
 u'1030050034F99000',
 u'1030010003390200',
 u'1030010007914D00',
 u'10300100048FDE00',
 u'10300100254DF300',
 u'10300100267ACD00',
 u'10300100252EBE00',
 u'10300100266A6200',
 u'103001001E10B700',
 u'103001002480AC00',
 u'1030010024043000',
 u'1030010010205A00',
 u'10300100088CF100',
 u'1030010010AF3000',
 u'1030010010429400',
 u'103001000ED36500',
 u'103001000D952D00',
 u'103001000FD41000',
 u'103001000FD5E300',
 u'103001000F3D1D00',
 u'1030010011A83400',
 u'10300100104F0B00',
 u'1030010010965400',
 u'1030010010B5F700',
 u'1030010010BCF200',
 u'1030010012D61500',
 u'1030010012B84D00',
 u'103001001D438400',
 u'10300100187B1F00',
 u'1030010019087B00',
 u'103001001DB85200',
 u'103001001E11FB00',
 u'103001001ABE2000',
 u'103001001ACB8500',
 u'103001001A425F00']

**Comment by chelm** [comment]
@joemcglinchy I was able to create a catalog image class object for all of those ids except: `103001000390AF00`

```
for i in ids:
    try:
        CatalogImage(i)
    except Exception as err:
        print err
```

And i verified that the one image that didnt work hasnt been ordered yet.

**Comment by chelm** [comment]
gonna close this again. It's not really a gbdxtools issue here, its more of a generic flaw that exists in the catalog itself.
