### ISSUE TITLE
gbdx.s3.download does not work

### ISSUE THREAD

**Issue by kkoperskidg** [DigitalGlobe/gbdxtools#230]
Windows, 
version 0.14.5 and 0.14.6 (both do not work)

>>> gbdx.s3.download("results/",".")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kkopersk\AppData\Local\Continuum\Anaconda2\lib\site-packages\gbdxtools\s3.py", line 90, in download
    for s3key in s3conn.list_objects(Bucket=bucket, Prefix=os.path.join(prefix, location))['Contents']:
  File "C:\Users\kkopersk\AppData\Local\Continuum\Anaconda2\lib\site-packages\botocore\client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\kkopersk\AppData\Local\Continuum\Anaconda2\lib\site-packages\botocore\client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied

Works with some older versions. seems to stop working more recently

**Comment by chelm** [comment]
This is really frustrating. I updating the s3 methods to use boto3 but i cannot get them to fail on any directory in my s3 bucket/user_prefix. 

It's clearly a permissions issue. 

@kkoperskidg If you get a chance would you mind installing a previous version, say 0.14.0 and making sure the same call works? Beyond i'll need to explore the props on you s3 bucket, etc.

**Comment by kkoperskidg** [comment]
I'll try. I can get files through the http://s3browser.geobigdata.io/ so I doubt permissions is an issue.
Doing some development so I will not change version now, but I will try later.
BTW Installation of gbdxtools on Windows is a real pain now for some reason. I pretty much have to nuke all conda as I can't change versions without errors (and I have gbdxtools as the only non-conda package now)

**Comment by chelm** [comment]
@kkoperskidg It dawned on me that this is a windows issue. I bet there are other issues I can clean up to make it easier on you for windows. Sorry about that. Will make it focus and experience it myself.

**Comment by kkoperskidg** [comment]
Thanks. We have a client who uses Windows only and I was helping him. I had to send him to support because i was not able to install gbdxtools from scratch.. They helped him, but then we have troubles with downloads.

**Comment by kkoperskidg** [comment]
gbdxtools version 0.14.1 works. It seems to broke sometime between this and 0.14.5

**Comment by chelm** [comment]
Great thanks @kkoperskidg - this has something to do me changing the s3 class to use boto3 instead of boto and i think is a windows issues inside boto3. Its a bummer but i'll find a solution

**Comment by kkoperskidg** [comment]
Created a working version in https://github.com/kkoperskidg/gbdxtools
os.path.join should not be used with S3 keys, just local files.
Will create pull request.

**Comment by chelm** [comment]
Thanks @kkoperskidg merged and 0.14.10 has the fix!
