### ISSUE TITLE
Look up bucket name for IdahoImage's 

### ISSUE THREAD

**Issue by chelm** [DigitalGlobe/gbdxtools#232]
Now that RDA is storing data in various buckets on S3 we need to support dynamically finding the bucket of an image in the image constructor for IdahoImage. 

I think best approach will be to attempt a look up when the `bucket` param is None. This way our classes like WorldView* will work as is and we wont incur another API hit.

**Comment by chelm** [comment]
@pramukta I think you're running into this with your newly ordered images. We have to support different buckets in s3 now so setting `bucket=rda-images-1` will work for newly ordered images. We'll do this automatically soon but for now that will unblock you. 

https://github.com/DigitalGlobe/gbdxtools/blob/master/gbdxtools/images/idaho_image.py#L18

**Comment by chelm** [comment]
@pramukta I've fixed this issue in dev.

**Comment by pramukta** [comment]
Ah got it cool, thanks! Will check it out now.
