### ISSUE TITLE
ordering radarsat2 data

### ISSUE THREAD

**Issue by joemcglinchy** [DigitalGlobe/gbdxtools#233]
Hello,

How do you order radarsat 2 data with gbdxtools? I am able to get successful results in a search with the vector query service, such as: 

```
{u'geometry': {u'coordinates': [[[[-105.61619, 40.86534],
      [-104.28127, 41.04077],
      [-104.0491, 39.95334],
      [-105.36254, 39.77713],
      [-105.61619, 40.86534]]]],
   u'type': u'MultiPolygon'},
  u'properties': {u'attributes': {u'archiveFac': u'PASS',
    u'archiveId': u'414845',
    u'beamMode': u'Extra Fine',
    u'beams': u'XF0W3',
    u'catalogID': u'610119',
    u'imageId': u'610119',
    u'imgCycle_int': 152,
    u'imgRelOrNo_dbl': 185.10520424,
    u'incidenceAngleNearRange_dbl': 38.33,
    u'lookDirection': u'Right',
    u'passDirection': u'Ascending',
    u'platformName': u'RADARSAT-2',
    u'polarizations': [u'HH'],
    u'sceneNo_int': 1,
    u'sensorPlatformName': u'RADARSAT-2',
    u'vendor': u'MacDonald, Dettwiler and Associates Ltd.'},
   u'format': None,
   u'id': u'610119_001',
   u'ingest_attributes': {u'_rest_url': u'http://vector.geobigdata.io/api/vectors/gbdx-alpha-catalog-v2-%257Bitem_date%253Ayyyy%257D',
    u'_rest_user': u'acquisitionsvc'},
   u'ingest_date': u'2018-01-10T22:03:47.774Z',
   u'ingest_source': u'GBDX_INGEST_ALPHA',
   u'item_date': u'2018-01-08T00:58:44.783Z',
   u'item_type': [u'GBDXCatalogRecord',
    u'Acquisition',
    u'MDAAcquisition',
    u'RADARSAT2'],
   u'name': None,
   u'original_crs': u'EPSG:4326',
   u'source': None,
   u'text': u''},
  u'type': u'Feature'})
```

but none of the IDs in there (archiveId, catID) are able to be used to successfully submit an order for the scene. I'm using the Auto-Order task to do that, but it fails with stdout:

[{'id': u'4817247957349865226',
  'name': u'Auto_Ordering_98e41726',
  'stdout': u'/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File "auto_ordering.py", line 119, in <module>\n    auto_ordering.run()\n  File "auto_ordering.py", line 112, in run\n    self.place_order()\n  File "auto_ordering.py", line 76, in place_order\n    raise Exception("Order Failed, Reason: {_response}".format(_response=response.content))\nException: Order Failed, Reason: \n{\n  "message" : "**Bad Request: 414845 is not valid catalog id**."\n}\n\n',
  'taskType': u'Auto_Ordering:0.0.1'}]

Also, I cannot use either archiveId or catID in the Postman API. To search a RADARSAT2 product and return metadata I have to use a Product_ID, something that starts with `PDS`. I tried using one of those IDs in the ordering task as well, but get the same "Bad Request" stdout message when the workflow fails.

Is it possible to order RADARSAT2 scenes with GBDX? I am running this from notebooks.geobigdata.io

**Comment by jeffnaus** [comment]
Ordering RADARSAT2 data is not supported by the GBDX ordering system.  There is a manual request required to order the data.  Please refer to the documentation here: https://gbdxdocs.digitalglobe.com/docs/mda-radarsat-2#section-order-mda-products for details.

**Comment by joemcglinchy** [comment]
I see. That is helpful, thank you!

**Comment by chelm** [comment]
For the time being Radarsat wont be available in gbdxtools, going to close.
