### ISSUE TITLE
Corrupt geotiff's off upper left hand corner of image

### ISSUE THREAD

**Issue by NickolasTobin** [DigitalGlobe/gbdxtools#234]
If you sample a particular catid in the upper left corner you get corrupt geotifs, insetting to about 150,150 is required.

catid='1040010030A9AF00'
img = CatalogImage(catid,  band_type='MS', proj='EPSG:4326', acomp=False, pansharpen=True)
sub = img[:,0:650,0:650]
sub.geotiff(path="corrupt.tif", proj='EPSG:4326')

**Comment by chelm** [comment]
@NickolasTobin I ran your code above. What about the tif is corrupt? 

`!gdalinfo corrupt.tif` >>

```
Driver: GTiff/GeoTIFF
Files: corrupt.tif
Size is 650, 650
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (69.120264930000005,34.609621891545096)
Pixel Size = (0.000002901545095,-0.000002901545095)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  69.1202649,  34.6096219) ( 69d 7'12.95"E, 34d36'34.64"N)
Lower Left  (  69.1202649,  34.6077359) ( 69d 7'12.95"E, 34d36'27.85"N)
Upper Right (  69.1221509,  34.6096219) ( 69d 7'19.74"E, 34d36'34.64"N)
Lower Right (  69.1221509,  34.6077359) ( 69d 7'19.74"E, 34d36'27.85"N)
Center      (  69.1212079,  34.6086789) ( 69d 7'16.35"E, 34d36'31.24"N)
Band 1 Block=650x1 Type=Float32, ColorInterp=Gray
Band 2 Block=650x1 Type=Float32, ColorInterp=Undefined
Band 3 Block=650x1 Type=Float32, ColorInterp=Undefined
Band 4 Block=650x1 Type=Float32, ColorInterp=Undefined
Band 5 Block=650x1 Type=Float32, ColorInterp=Undefined
Band 6 Block=650x1 Type=Float32, ColorInterp=Undefined
Band 7 Block=650x1 Type=Float32, ColorInterp=Undefined
Band 8 Block=650x1 Type=Float32, ColorInterp=Undefined
```

**Comment by chelm** [comment]
```python
with rasterio.open('corrupt.tif') as src:
    print src.meta
```

```
{'count': 8, 'crs': CRS({'init': u'epsg:4326'}), 'dtype': 'float32', 'affine': Affine(2.901545095220985e-06, 0.0, 69.12026493,
       0.0, -2.901545095220985e-06, 34.609621891545096), 'driver': u'GTiff', 'transform': (69.12026493, 2.901545095220985e-06, 0.0, 34.609621891545096, 0.0, -2.901545095220985e-06), 'height': 650, 'width': 650, 'nodata': None}
```

**Comment by NickolasTobin** [comment]
when viewed its all black, if you do an rgb it can be all red variations of the underlying terrain. Various viewing problems in qgis. I'll find a good one tonight and attach it to this with exact coordinates.

**Comment by chelm** [comment]
The values in the geotiff are preserved for analytical sake. This is not good for viewing the data. You can scale the tif with gdal translate or create tiff in python that scales the data to RGB (0,255) for viewing. 

`gdal_translate -b 1 -b 2 -b 3 -mask "none" "input.tif" "output.tif" -scale`

**Comment by NickolasTobin** [comment]
Chris do you have a phone number I could speak to you on?

**Comment by NickolasTobin** [comment]
from gbdxtools import CatalogImage
from osgeo import ogr
import os
from pprint import pprint
import rasterio


catid='1040010030A9AF00' #2017-08-11
img = CatalogImage(catid, band_type='MS', proj='EPSG:4326', acomp=False, pansharpen=True)
#img = CatalogImage(catid, bbox=bbox, band_type='MS', proj='EPSG:4326', acomp=False, pansharpen=True,product='acomp')
print img.shape
sub = img[:,0:650,0:650]

rgb = sub[[4,2,1],:,:]

print sub.shape
sub.geotiff(path=r'corrupt.tif', proj='EPSG:4326')
rgb.geotiff(path=r'corrupt_rgb.tif', proj='EPSG:4326')

**Comment by NickolasTobin** [comment]
Put the corrupt_rgb.tif into QGis. The values are all wonkie, negative values included.

**Comment by chelm** [comment]
Agree the data are wonky. Agree that in Qgis its pretty bad due to those negative values. But i think its an issue in the image on the server, not a gbdxtools issue. 

However. Here's a way to create tifs as uint16 values that will render cleanly in qgis: 

```python
# cast as uint16...
sub = img[:,0:650,0:650].astype('uint16')

sub.geotiff(path=r'corrupt.tif', proj='EPSG:4326')
sub.geotiff(path=r'corrupt_rgb.tif', proj='EPSG:4326', bands=[4,2,1])
```
