### ISSUE TITLE
PyJWT version mismatch

### ISSUE THREAD

**Issue by lababidi** [DigitalGlobe/gbdxtools#236]
I'm getting a mismatch of version numbers for PyJWT. is this really a necessity on the version?
```error: PyJWT 1.6.0 is installed but PyJWT==1.4.2 is required by {'gbdx-auth'}```

**Comment by chelm** [comment]
@lababidi gbdxtools doesnt actually require pyJWT, its a dep in gbdx-auth: 

https://github.com/TDG-Platform/gbdx-auth/blob/master/requirements.txt#L4

I dont think its a great idea to that have pinned but we should bring up the issue in that repo.

**Comment by chelm** [comment]
This has been resolved in gbdx-auth and we'll have the latest dep updated here soon
