### ISSUE TITLE
Request: requirements clean-up

### ISSUE THREAD

**Issue by jambonrose** [DigitalGlobe/gbdxtools#238]
When installing the package with `pip`, `gbdxtools` will install packages like `pytest` and `bumpversion`, which are for developing the project rather than using the project. However, the package doesn't request items like `rasterio`, necessary for some of the features used by `gbdxtools` (but thankfully, the code-base warns developers that it's missing).

I'm requesting that the project clean up what gets installed along with `gbdxtools`, making installations more lightweight (particularly helpful in Docker environments). Additionally, the use of `setup.py` `extras` could allow conditional includes of packages like `rasterio`, allowing for installations along the following lines:

- `pip install gbdxtools[all]`
- `pip install gbdxtools[geotiff]`
- `pip install gbdxtools`

The last would be the most minimal installation.

Thanks for taking the time to consider this.

**Comment by chelm** [comment]
@jambonrose I dig it! Love the idea. 

Any chance of making a PR to get this supported sooner?

**Comment by jambonrose** [comment]
@chelm Thanks for considering this!

While some of these tools fit into obvious categories (`mock` and `pytest` never need to be installed by library consumers, for instance), I think some of the choices require input from Digital Globe's clients. e.g.: How many are using `boto3` to access S3 and in what use-cases? Are those use-case expected, causing `boto3` to be installed by default, or is that one of the extra installs?

What's more, I would have included `rasterio` by default, but by the look of the commit log, that gets dicey on Windows. What are the chances Mapbox would consider releasing Windows binaries on PyPI as part of the upcoming 1.0 release? Perhaps that's a silly question: I am not familiar with `rasterio` on Windows, but an upstream fix might make things easier here.

Finally, I suspect some of the clean up may lead to code changes: 
- `toolz` is installed and imported twice, but only actually used once, and that code can be replaced by the standard library's `itertools.chain.from_iterable(seqs)`.
- Is `cloudpickle` actually ever used in the codebase (I see that you removed it and added it back in last year, but I am not clear why)?
- In a different vein, `pycurl` and `requests` fulfill many similar needs. Does `gbdxtools` need both? I'm not familiar enough with the design choices made here, and these are not decisions I can make as a non-DG consumer on the library.

Given all this, while I'm happy to provide input, I'm not the right person to implement this.

Regardless of any other changes, I would urge you to pin or limit the versions of all the dependencies being required.

Quick overview based on my rapid perusal of the code:

- testing/development (separate requirements file)
    - bumpversion 
    - mock
    - pytest
    - pytest-runner
    - setuptools==39.0.1
    - vcrpy
- minimal/core
    - configparser
    - future>=0.15.2
    - gbdx-auth==0.2.6
    - pycurl
    - requests_futures
    - requests>=2.12.1
    - six>=1.10.0
- unknown or extras of some sort
    - affine
    - boto3
    - cachetools >= 2.0.0
    - cloudpickle
    - dask >= 0.16.0
    - ephem
    - mercantile>=0.10.0
    - numpy
    - pyproj
    - scikit-image
    - shapely
    - toolz

**Please note the addition of `setuptools`**, as (ime) pinning this helps avoid strange errors when creating packages.

I'm assuming use of some libraries across the system, but that that may not be true for items like `requests` and `pycurl`, which may be used exclusively in different sections, so please take the list with a grain of salt.

**Comment by jambonrose** [comment]
Side note: PyPA now officially recommends the use of `pipenv`: https://packaging.python.org/tutorials/managing-dependencies/#managing-dependencies
