### ISSUE TITLE
gbdxtools.auth fails silently

### ISSUE THREAD

**Issue by sumarlidason** [DigitalGlobe/gbdxtools#240]
_Auth constructor catches oAuth exception; leaving gbdx_connection object uninitialized and leads to unexpected behaviors.

suggest one of
* creation of custom gbdx general authentication failure `Exception`, and raising this
* removal of try/catch since we can't recover, allowing oAuth errors to propagate descriptively to the caller

**Comment by jambonrose** [comment]
I believe this is related: TDG-Platform/gbdx-auth#10

I am in favor of the second choice: allow the authentication code to fail noisily, in-turn allowing the developer consuming `gbdxtools` to handle the error gracefully, rather than ending up in a state that cannot easily be recovered from.

**Comment by sumarlidason** [comment]
Tried to create PR, need write permission.

**Comment by jambonrose** [comment]
@sumarlidason I may be misunderstanding the problem, but: typically, on Github, you don't push code to another person or group's codebase. You fork the repository to your own account. You then create a new git branch, commit any code/changes to this branch, and then push the new branch to your forked repository. Once you've pushed the code to your github repo, you'll be able to open a PR from your repository to this repository (called the upstream repository).

Hope that helps, but let me know if I've misunderstood the difficulty you're having.

Full disclosure: I am not affiliated with Digital Globe.

**Comment by sumarlidason** [comment]
I work at DigitalGlobe, and sit next to some GBDX folks. I should not be treated as an external user.

**Comment by jambonrose** [comment]
Welp, that's embarrassing. Sorry about that, was just trying to be helpful.

**Comment by chelm** [comment]
@jambonrose Thanks for helping out! I agree the 2nd option is preferable.

@sumarlidason Regardless of being a DG employee or not you can still make a PR by forking/branching the repo. We'd love to have your PR though! If you'd like write permissions to push branches directly to the repo I can grant that to you.

**Comment by sumarlidason** [comment]
I will escalate up my mgmt chain, this isn't the SOP from what i've seen. We are supposed to be encouraging collaboration.

**Comment by chelm** [comment]
We here in gbdxtools land are 100% all about collaboration. Nothing at all should prevent you from contributing code!

**Comment by sumarlidason** [comment]
<3 PR created.

https://github.com/DigitalGlobe/gbdxtools/pull/241

**Comment by chelm** [comment]
@sumarlidason you are now a member of the `gbdxtools_contributors` - should be able to push branches directly to the repo.
