### ISSUE TITLE
pip install gbdxtools failing

### ISSUE THREAD

**Issue by carolynpjohnston** [DigitalGlobe/gbdxtools#27]
Bottom line:

> Command "/mnt/tier2/cjohnsto/miniconda2/envs/cjbase/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-YIZK6J/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-sbFikc-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-YIZK6J/cffi/ 

more details below.

--- snippety ---

   c/_cffi_backend.c:3790: error: \u2018ffi_type_double\u2019 undeclared (first use in this function)
    c/_cffi_backend.c:3798: error: \u2018ffi_type_longdouble\u2019 undeclared (first use in this function)
    c/_cffi_backend.c:3805: error: \u2018ffi_type_uint8\u2019 undeclared (first use in this function)
    c/_cffi_backend.c:3806: error: \u2018ffi_type_uint16\u2019 undeclared (first use in this function)
    c/_cffi_backend.c:3807: error: \u2018ffi_type_uint32\u2019 undeclared (first use in this function)
    c/_cffi_backend.c:3808: error: \u2018ffi_type_uint64\u2019 undeclared (first use in this function)
    c/_cffi_backend.c: At top level:
    c/_cffi_backend.c:4444: error: expected specifier-qualifier-list before \u2018ffi_type\u2019
    c/_cffi_backend.c:4463: error: expected \u2018=\u2019, \u2018,\u2019, \u2018;\u2019, \u2018asm\u2019 or \u2018__attribute__\u2019 before \u2018_\u2019 token
    c/_cffi_backend.c: In function \u2018fb_build\u2019:
    c/_cffi_backend.c:4603: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018atypes\u2019
    c/_cffi_backend.c:4603: error: \u2018ffi_type\u2019 undeclared (first use in this function)
    c/_cffi_backend.c:4603: error: expected expression before \u2018)\u2019 token
    c/_cffi_backend.c:4604: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018nargs\u2019
    c/_cffi_backend.c:4607: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018rtype\u2019
    c/_cffi_backend.c:4607: warning: implicit declaration of function \u2018fb_fill_type\u2019
    c/_cffi_backend.c:4615: error: \u2018cif_description_t\u2019 has no member named \u2018exchange_offset_arg\u2019
    c/_cffi_backend.c:4618: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018rtype\u2019
    c/_cffi_backend.c:4619: error: \u2018ffi_arg\u2019 undeclared (first use in this function)
    c/_cffi_backend.c:4629: error: \u2018atype\u2019 undeclared (first use in this function)
    c/_cffi_backend.c:4642: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018atypes\u2019
    c/_cffi_backend.c:4643: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018atypes\u2019
    c/_cffi_backend.c:4646: error: \u2018cif_description_t\u2019 has no member named \u2018exchange_offset_arg\u2019
    c/_cffi_backend.c:4655: error: \u2018cif_description_t\u2019 has no member named \u2018exchange_size\u2019
    c/_cffi_backend.c: In function \u2018fb_build_name\u2019:
    c/_cffi_backend.c:4679: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018nargs\u2019
    c/_cffi_backend.c:4691: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018fct\u2019
    c/_cffi_backend.c:4694: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018fct\u2019
    c/_cffi_backend.c: In function \u2018fb_prepare_ctype\u2019:
    c/_cffi_backend.c:4738: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018fct\u2019
    c/_cffi_backend.c:4755: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018fct\u2019
    c/_cffi_backend.c: At top level:
    c/_cffi_backend.c:4775: error: expected declaration specifiers or \u2018...\u2019 before \u2018ffi_abi\u2019
    c/_cffi_backend.c: In function \u2018fb_prepare_cif\u2019:
    c/_cffi_backend.c:4802: warning: implicit declaration of function \u2018ffi_prep_cif\u2019
    c/_cffi_backend.c:4802: error: \u2018cif_description_t\u2019 has no member named \u2018cif\u2019
    c/_cffi_backend.c:4802: error: \u2018fabi\u2019 undeclared (first use in this function)
    c/_cffi_backend.c:4802: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018nargs\u2019
    c/_cffi_backend.c:4803: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018rtype\u2019
    c/_cffi_backend.c:4803: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018atypes\u2019
    c/_cffi_backend.c:4803: error: \u2018FFI_OK\u2019 undeclared (first use in this function)
    c/_cffi_backend.c: In function \u2018new_function_type\u2019:
    c/_cffi_backend.c:4847: error: too many arguments to function \u2018fb_prepare_cif\u2019
    c/_cffi_backend.c:4861: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018nargs\u2019
    c/_cffi_backend.c:4871: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018nargs\u2019
    c/_cffi_backend.c:4881: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018nargs\u2019
    c/_cffi_backend.c:4884: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018nargs\u2019
    c/_cffi_backend.c:4885: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018nargs\u2019
    c/_cffi_backend.c:4887: error: \u2018struct funcbuilder_s\u2019 has no member named \u2018nargs\u2019
    c/_cffi_backend.c: In function \u2018b_new_function_type\u2019:
    c/_cffi_backend.c:4898: error: \u2018FFI_DEFAULT_ABI\u2019 undeclared (first use in this function)
    c/_cffi_backend.c: In function \u2018convert_from_object_fficallback\u2019:
    c/_cffi_backend.c:4918: error: \u2018ffi_arg\u2019 undeclared (first use in this function)
    c/_cffi_backend.c: At top level:
    c/_cffi_backend.c:5100: error: expected \u2018)\u2019 before \u2018_\u2019 token
    c/_cffi_backend.c: In function \u2018prepare_callback_info_tuple\u2019:
    c/_cffi_backend.c:5142: error: \u2018ffi_arg\u2019 undeclared (first use in this function)
    c/_cffi_backend.c: In function \u2018b_callback\u2019:
    c/_cffi_backend.c:5175: error: \u2018ffi_closure\u2019 undeclared (first use in this function)
    c/_cffi_backend.c:5175: error: \u2018closure\u2019 undeclared (first use in this function)
    c/_cffi_backend.c:5185: warning: implicit declaration of function \u2018cffi_closure_alloc\u2019
    c/_cffi_backend.c:5203: warning: implicit declaration of function \u2018ffi_prep_closure\u2019
    c/_cffi_backend.c:5203: error: \u2018cif_description_t\u2019 has no member named \u2018cif\u2019
    c/_cffi_backend.c:5204: error: \u2018invoke_callback\u2019 undeclared (first use in this function)
    c/_cffi_backend.c:5204: error: \u2018FFI_OK\u2019 undeclared (first use in this function)
    In file included from c/cffi1_module.c:3,
                     from c/_cffi_backend.c:6561:
    c/realize_c_type.c: In function \u2018realize_c_type_or_func\u2019:
    c/realize_c_type.c:577: error: \u2018FFI_DEFAULT_ABI\u2019 undeclared (first use in this function)
    c/_cffi_backend.c: In function \u2018init_cffi_backend\u2019:
    c/_cffi_backend.c:6653: error: \u2018FFI_DEFAULT_ABI\u2019 undeclared (first use in this function)
    error: command 'gcc' failed with exit status 1

```
----------------------------------------
```

Command "/mnt/tier2/cjohnsto/miniconda2/envs/cjbase/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-YIZK6J/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-sbFikc-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-YIZK6J/cffi/
(cjbase)[cjohnsto@r01n08:~]$

**Comment by nricklin** [comment]
what OS are you on?

looks like it's having trouble installing "cffi".

**Comment by carolynpjohnston** [comment]
yeah I got it working
I needed to pip install cryptography separately
it was able to install cffi correctly. It's kind of a mystery.

On Mon, May 2, 2016 at 3:38 PM, Nate Ricklin notifications@github.com
wrote:

> what OS are you on?
> 
> looks like it's having trouble installing "cffi".
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/DigitalGlobe/gbdxtools/issues/27#issuecomment-216372246

## 

_Carolyn P. Johnston, Ph.D._
Digitalglobe, Inc.
Mobile: 303-304-6369
Twitter: @GeostatsCarolyn
LinkedIn: https://www.linkedin.com/in/carolyn-p-johnston-5761956

**Comment by nricklin** [comment]
ok, maybe we can reduce the number of dependencies we have.  That one is used by gbdx-auth, which requires requests[security].  Not sure how essential it is.
