### ISSUE TITLE
baselayermatch not working

### ISSUE THREAD

**Issue by mjgleason** [DigitalGlobe/gbdxtools#272]
Two issues are keeping base_layer_match() from working within GBDX Notebooks:

1. rio_hist isn't a required dependency. If it is not present, the meta model still loads (https://github.com/DigitalGlobe/gbdxtools/blob/26eb0a27366633c6c55f1371976ef5c05da66a37/gbdxtools/images/meta.py#L19-L22), but the histogram_match() function is not available, which causes base_layer_match() to fail here: https://github.com/DigitalGlobe/gbdxtools/blob/26eb0a27366633c6c55f1371976ef5c05da66a37/gbdxtools/images/meta.py#L541. Some possible solutions are to (1) make rio_hist a required dependency, or (2) add some error handling around L541 referenced above to explain why this failure occurs and how to fix it (e.g., ```Have you installed the rio_hist library? If not, try pip install rio_hist and reload gbdxtools.```
2. The environment variable that stores the required API key is now called 'MAPBOX_API_KEY', but is still in the source code as 'DG_MAPS_API_TOKEN'. See: https://github.com/DigitalGlobe/gbdxtools/blob/2bff57b18d74cee6ac6ad5df30e56256165f961c/gbdxtools/images/tms_image.py#L185

**Comment by chelm** [comment]
@mjgleason Thanks! I've known about these issues for a little while, just needed to be reminded. Will work on solutions.

**Comment by chelm** [comment]
Also worth mentioning that rio_hist will be included as a required dep. We no require rasterio as a required dep, and this needs to follow suit.

**Comment by chelm** [comment]
This issue is fixed. However i noticed that we are forcibly preventing BLM on geoeye imagery... trying to still understand why we're doing that
