### ISSUE TITLE
Error during gbdxtools installation?

### ISSUE THREAD

**Issue by kstamatiou** [DigitalGlobe/gbdxtools#28]
Started with fresh venv on Ubuntu, then pip install gbdxtools.
Got:
Cleaning up...
Command /home/ubuntu/venv2/bin/python -c "import setuptools, tokenize;**file**='/home/ubuntu/venv2/build/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-MfenRk-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/venv2/include/site/python2.7 failed with error code 1 in /home/ubuntu/venv2/build/cryptography
Traceback (most recent call last):
  File "/home/ubuntu/venv2/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/venv2/local/lib/python2.7/site-packages/pip/**init**.py", line 185, in main
    return command.main(cmd_args)
  File "/home/ubuntu/venv2/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 28: ordinal not in range(128)

**Comment by longbotham** [comment]
I had and have seen multiple problems with pip installing cryptography (plus cffi) and pillow.  I'm able to solve both on linux with an install from conda.  About the only things we can do on our front is provide documentation to help get around these pip issues or to remove the dependencies.  I'm planning on writing up a short intro and some examples for conda - a link to that once it is done could help on the former solution.

**Comment by kstamatiou** [comment]
It looks like pip is having trouble with cryptography. 
Can we remove this dependency and find a workaround?

**Comment by kstamatiou** [comment]
Closing this. It is the same as #29.
