### ISSUE TITLE
Installing gbdxtools via conda in python 3 downgrades python version to 2.7

### ISSUE THREAD

**Issue by chelm** [DigitalGlobe/gbdxtools#289]
There is some dep in our conda builds that is downgrading python and a few other packages. When you do not specify `-c conda-forge` as a channel.

**Comment by chelm** [comment]
when using a python 3 env and installing via `conda install -c digitalglobe gbdxtools` python gets downgraded.

**Comment by drwelby** [comment]
The problem I had (`module 'gbdxtools' has no attribute 'images'`) seems to occur only if I'm starting iPython when in the `gbdxtools` directory.

**Comment by chelm** [comment]
@drwelby Ahh that makes sense. Python is importing the gbdxtools dir in that case, not the installed module.

**Comment by chelm** [comment]
Verified that this issues is an issue with a few deps that dont exist in default channels. Sounds like anaconda is possibly going to add support for including build channels in the meta.yaml files but currently we build with `-c conda-forge` and must install with it as well (when using conda)

**Comment by joemcglinchy** [comment]
Hello, I am running into this issue as well (downgrading to py2.7 from 3.6) and when I try to install from `conda-forge`, the package is not available from that channel. 

Also, when I try to install from `digitalglobe` channel here is the list of downgrades. There are a lot of packages being downgraded to 2.7 and would pretty much break the environment. 

```
The following packages will be DOWNGRADED:

    fiona:                         1.7.13-py36hb00a9d7_2               conda-forge  --> 1.7.12-py27h3f37509_0           
    gdal:                          2.2.4-py36hb00a9d7_1                conda-forge  --> 2.2.2-py27hae9aa10_1            
    kiwisolver:                    1.0.1-py36_1                        conda-forge  --> 1.0.1-py27hf484d3e_0            
    matplotlib:                    2.2.2-py36_1                        conda-forge  --> 2.2.2-py27h0e671d2_0            
    pandas:                        0.23.3-py36hf8a1672_1               conda-forge  --> 0.23.3-py27h04863e7_0           
    pip:                           18.0-py36_0                         conda-forge  --> 10.0.1-py27_0                   
    psycopg2:                      2.7.5-py36hdffb7b8_1                conda-forge  --> 2.7.3.1-py27h1368252_0          
    pysal:                         1.14.4.post1-py36_0                 conda-forge  --> 1.14.3-py27_0                   
    python:                        3.6.4-hc3d631a_1                                 --> 2.7.14-h1571d57_29              
    pytorch:                       0.4.1-py36_cuda9.0.176_cudnn7.1.2_1 pytorch      --> 0.4.0-py27hdf912b8_0            
    rasterio:                      1.0.1-py36h1b5fcde_1                conda-forge  --> 0.36.0-py27h3f37509_2           
    setuptools:                    40.0.0-py36_0                       conda-forge  --> 39.2.0-py27_0                   
    shapely:                       1.6.4-py36h164cb2d_1                conda-forge  --> 1.6.4-py27h7ef4460_0            
    sqlalchemy:                    1.2.10-py36h470a237_1               conda-forge  --> 1.2.10-py27h14c3975_0           
    torchvision:                   0.2.1-py36_1                        pytorch      --> 0.2.1-py27_0                    
    tornado:                       5.1-py36_0                          conda-forge  --> 5.0.2-py27h14c3975_0 
```

**Comment by chelm** [comment]
have you tried `conda install -y -c conda-forge -c digitalglobe gbdxtools`?

**Comment by chelm** [comment]
ping @joemcglinchy

**Comment by joemcglinchy** [comment]
@chelm sorry to go MIA. I am trying this again and seeing that maybe python 3.6 is not currently supported. I got the above working in a python 3.5 environment.

**Comment by joemcglinchy** [comment]
I'll also add, I was able to successfully install gbdxtools with python 3.6.4, but not python 3.6.5

**Comment by bpstewar** [comment]
Bumping this because I am having the same problem - how do I install gbdxtools with python 3.6.*?

Joe, what was your command that successfully installed the package?

**Comment by chelm** [comment]
I'll be able to revisit this on Monday, but i am running gbdxtools all over the place in 3.6 so will get to the bottom of this. 

I do remember a certain dep being the primary issue here a while back.

**Comment by bpstewar** [comment]
I managed to get it by downloading the package from github, running setup.py, and then manualling installing a couple libraries that errored: ephem and scikit-image.

I think the error lies in the ephem package, but that is just a hunch

**Comment by chelm** [comment]
I think you're right, i remember ephem being the one

**Comment by chelm** [comment]
So we install gbdxtools in our Notebooks product and run under python 2.7 and python 3.6.6.

**Comment by chelm** [comment]
the command we use to install `conda install -n gbdx_py3 -c conda-forge -c digitalglobe -y gbdxtools=0.15.12`

Will do some more exploring...

**Comment by joemcglinchy** [comment]
so this works in python == 3.6.5? just curious on that. I can see about moving the environment I'm using to python 3.6.6 or staying at 3.6.4.

@bpstewar I was using `conda install -y -c conda-forge -c digitalglobe gbdxtools`
