### ISSUE TITLE
Reconsider dependencies (installation problems)

### ISSUE THREAD

**Issue by kstamatiou** [DigitalGlobe/gbdxtools#29]
Pillow: There is only one line of code that uses Pillow it in idaho.py to save an image to disk. Can we avoid importing Pillow?

**Comment by kstamatiou** [comment]
cryptography

I am running into problems installing gbdxtools with pip in a fresh venv. Excerpt from the error message:

Running setup.py install for cffi ... error
    Complete output from command /home/ubuntu/venv/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-hbFJYI/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-QF4CLJ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/venv/include/site/python2.7/cffi:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing`libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing`libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found

**Comment by kstamatiou** [comment]
@longbotham has suggested conda for a more stable installation environment.

**Comment by kstamatiou** [comment]
I have been able to install gbdxtools in a clean virtual environment on my mac. So, is this a linux problem?

**Comment by longbotham** [comment]
Just a different in platform, they have different requirements - https://cryptography.io/en/latest/installation/  http://cffi.readthedocs.io/en/latest/installation.html

**Comment by kstamatiou** [comment]
For Ubuntu:

Installing
sudo apt-get install build-essential libssl-dev libffi-dev python-dev
solves the problem with cryptography.

Installing
sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
solves the problem with Pillow. 

Are we ok with these solutions? They violate our one-line-installation mantra. 

Pillow should go. It's practically not used in this version and is not worth the trouble.

Who can comment on the importance of cryptography?

Presently, I have added basic troubleshooting instructions to the readme.

**Comment by kstamatiou** [comment]
The only function that used Pillow was idaho.get_tile_by_zxy(). This function was broken so I removed it. With it goes the dependence on Pillow.

Pillow was used to save a tif. Can't this be done with

```
        with open(file_path, 'wb') as the_file:
            the_file.write(r.content)
```

as in the function get_idaho_chip()?
