### ISSUE TITLE
Depricate the use of `IPE` in general and convert to `RDA` where it makes sense

### ISSUE THREAD

**Issue by chelm** [DigitalGlobe/gbdxtools#293]
IPE is used within the code base to reference various aspects of data on image classes (eg `image.ipe_id` or `image.ipe_metadata`). Since the backend platform component that was IPE is now called "RDA" we need to switch in order to avoid any prolonged confusion. 

IPE, or "Image Processing Engine" - changed its name to RDA, or "Raster Data Access" and is the backing API to gbdxtools' image classes. It supports deferred execution graphs to virtual represent images as wholes from a series of tiles that are generated from a graph in an on demand way. 

In the code base we'd like to rename anything containing the term "IPE or ipe_*" that is externally facing to be more generic, no longer any refs to IPE or RDA. Interal methods or classes can just switch to RDA. 

The tricky part of this is determining how we implement a proper deprication in favor of a new property or method.

**Comment by drwelby** [comment]
Addressed in #369
