### ISSUE TITLE
Unable to instantiate 1B IdahoImages

### ISSUE THREAD

**Issue by pramukta** [DigitalGlobe/gbdxtools#308]
So when trying to instantiate a 1B IdahoImage the following happens:

```Python
from gbdxtools import IdahoImage
img0 = IdahoImage("0c0430ae-3f6a-4743-939a-438da354afb4", product="1b")
print(img0.options["product"] # should be "1b")
```
`toa_reflectance`

This was observed on notebooks.geobigdata.io and it's the following block in the IdahoImage constructor that caused it on there (it overrides the selected option):

```Python
        if options["acomp"] and options["bucket"] != "idaho-images":
            options["product"] = "acomp"
        else:
            options["product"] = "toa_reflectance" 
```

Not sure where it is / if it is relevant after the large driver refactor but is the issue as deployed.

**Comment by chelm** [comment]
There are a few issues here. First is that GBDXNotebooks is not up-to-date with the latest gbdxtools release (v0.14.10 vs v0.15.0), which has changed a bit regarding the use of `product`. Together with some changes in RDA, gbdxtools is now creating a single graph per image, so the concept of `product` is gone in >=0.15.0. 

However, even in 0.15.0 there are issues related to fetching a 1b image. First is that now IdahoImage should support a `spec="1b"` but in the current release its a bug that spec is not being passed to the image (easy fix). Beyond that though there is another bug related to the recent refactor and introduction of RDAGeoAdapter that is expecting spatial metadata that is not present when fetching 1b data. 

I think what this means though is our test coverage isnt good enough around idaho imagery and all of its options, else this would have been caught pre-release. Will fix and cut a release soon.

**Comment by pramukta** [comment]
Cool, sounds good, thanks.

**Comment by chelm** [comment]
Released. 

```
from gbdxtools import IdahoImage
img0 = IdahoImage("0c0430ae-3f6a-4743-939a-438da354afb4", spec="1b")
print(img0.ipe.graph())
```

the graph is just a straight up IdahoRead with no ortho etc. just raw 1b/DN.

**Comment by chelm** [comment]
version > 0.15.1
