### ISSUE TITLE
get_idaho_chip.py

### ISSUE THREAD

**Issue by kstamatiou** [DigitalGlobe/gbdxtools#31]
@jeffnaus: I ran this example, but the tiff was not created.

Also: are all the imports necessary?

**Comment by nricklin** [comment]
This fails with this error when I try it:

```
Retrieving IDAHO chip


Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/private/tmp/blah/venv/lib/python2.7/site-packages/gbdxtools/idaho.py", line 222, in get_idaho_chip
    file_path = os.path.join(output_folder, idaho_id+'.tif')
  File "/private/tmp/blah/venv/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by jeffnaus** [comment]
I think the problem would be with this line:

temp_path = os.environ.get('temp')

What results do you get from running this?

**Comment by nricklin** [comment]
I get None

**Comment by jeffnaus** [comment]
do you have a temp_path = os.environ.get('tmp') ?

**Comment by nricklin** [comment]
I don't have an env var showing where /tmp is

**Comment by jeffnaus** [comment]
Ok, found a better way of finding the temp dir.  I'll make a new pull request.

**Comment by jeffnaus** [comment]
import tempfile
temp_path = tempfile.gettempdir()

**Comment by kstamatiou** [comment]
This works now. Closing.
