### ISSUE TITLE
1030010058285700 - missing IDAHO metadata??

### ISSUE THREAD

**Issue by loominator1970** [DigitalGlobe/gbdxtools#317]
I attempted to run CatalogImage the following strip and received this error

gbdxtools.ipe.error.MissingIdahoImages: Unable to find IDAHO imagery in the catalog: item_type:IDAHOImage AND attributes.catalogID:1030010058285700 AND attributes.colorInterpretation:WORLDVIEW_8_BAND

Here is the section in the code where it failed

catalog_id = '1030010058285700'  # fail
bounds = '0.906774935764, 41.0039707081, 0.910998264341, 41.0099707081'

img = CatalogImage(catalog_id,bbox=map(float, bounds.split(",")),band_type='MS',proj="EPSG:4326",acomp=False,pansharpen=True)

**Comment by chelm** [comment]
This looks to be a broken record in the catalog. If you search the catalog for the CatID you get 13 records one is the acquisition and 12 are products. there are no IdahoImagery in the catalog, hence the error. 

I am unsure of the best path to getting this resolved but i think this falls into @jeffnaus space.
