### ISSUE TITLE
Set stretch to [0,100] by default when using blm = True

### ISSUE THREAD

**Issue by mjgleason** [DigitalGlobe/gbdxtools#354]
This is just an idea, but one worth exploring. When using blm, it's probably not necessary to also do the normal truncate + stretch as a precursor to histogram matching. Here's an example where setting the stretch to [0,100] helps.

With current defaults (stretch=[2,98]):
![image](https://user-images.githubusercontent.com/24549594/41785980-76e76a9e-7601-11e8-917a-357c10e69788.png)

With stretch=[0,100]:
![image](https://user-images.githubusercontent.com/24549594/41786002-8976745c-7601-11e8-92a8-78560e8c39d0.png)

**Comment by chelm** [comment]
but that first image is just purely magical...
