### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by nricklin** [DigitalGlobe/gbdxtools#36]
We need release notes.  

It'd be nice to have one simple text file that we can update when doing releases, and it'd be viewable both on the github readme and in readthedocs.

**Comment by nricklin** [comment]
ok well I created a changelog.md file:
https://github.com/DigitalGlobe/gbdxtools/blob/master/changelog.md

**Comment by kstamatiou** [comment]
I deem this to be good enough for the time being. Closing.
