### ISSUE TITLE
Fix bug in ordering.order()

### ISSUE THREAD

**Issue by kstamatiou** [DigitalGlobe/gbdxtools#37]
@dmitryzv 

If image_catalog_ids is a string this will not work:

sanitized_ids = [id_.strip() for id_ in set(image_catalog_ids) if id_]

Please fix this. order() is expected to work with both 'catid' and ['catid']

**Comment by nricklin** [comment]
Kostas, you should create tests for this behavior that are expected to
pass.

**Comment by dmitryzv** [comment]
In fact such test exists. And it passed in my previous commit. It still passes even without fixing the bug (which is definitely there).
I think that vcr library doesn’t look into request body and because there is a cassette file for the test it just returned a response from previous run.

**Comment by kstamatiou** [comment]
Closed.
