### ISSUE TITLE
Launch workflow with CATID as argument.

### ISSUE THREAD

**Issue by nricklin** [DigitalGlobe/gbdxtools#4]
_From @kostasthebarbarian on April 2, 2016 0:26_

As a user, I expect to be able to launch workflows and enter a catalog identifier (CATID) instead of an S3 location. If the image is not existent in GBDX, it is automatically ordered as part of the workflow.

_Copied from original issue: kostasthebarbarian/gbdxtools#16_

**Comment by kstamatiou** [comment]
Do we still want this? Closing until further discussion.
