### ISSUE TITLE
Add plot method for 8 bit RGBs that don't need balancing

### ISSUE THREAD

**Issue by drwelby** [DigitalGlobe/gbdxtools#401]
8 bit RGB images should probably be plotted without any adjustment. They don't need to be ranged anyway. It's probably safe to assume that they're well balanced.

This problem is most evident with things like some of ML result images which are really just classified. An image which is either red (#FF0000 or black (#000000) has no dynamic range and the default contrast stretch will error since there is no range to work with. 

Images with no dynamic range should probably skip balancing.

This could be also handled with an option like `histogram='ignore'` which would pass through the data without any adjustment.

**Comment by drwelby** [comment]
Plotting an ML image as a single band using a custom colormap works well:

```python
from matplotlib import colors
# make a colormap to treat 255 as red, 0 as transparent
cmap = colors.ListedColormap(['#00000000', 'red'])
bounds=[0,128,255]
norm = colors.BoundaryNorm(bounds, cmap.N)
# plot the first (red) band using the custom colormap
plt.imshow(seg[0,:,:].compute(), alpha=.5, origin='lower', cmap=cmap, norm=norm)
```

**Comment by chelm** [comment]
This is complete correct?

**Comment by drwelby** [comment]
Yes
