### ISSUE TITLE
Missing deprecations

### ISSUE THREAD

**Issue by drwelby** [DigitalGlobe/gbdxtools#404]
Classes and methods that have been deprecated but are missing warnings and/or reverse compatibility.

**Comment by drwelby** [comment]
`image.blm_match()` is used in some notebooks. It was superseded by `image.rgb(histogram='match')`.

**Comment by leatkinson** [comment]
`IpeImage` replaced by `RDAImage `
`from gbdxtools.ipe.interface import Ipe ` replaced by `from gbdxtools.rda.interface import RDA `
ipe attribute of Image Objects replaced by rda attribute.

**Comment by drwelby** [comment]
`ipe.metadata` to `.metadata`

**Comment by chelm** [comment]
the ipe deprecations i think have been taken care of, should re-add `blm_match` with a deprecation?

**Comment by drwelby** [comment]
I have a fix in here:

https://github.com/DigitalGlobe/gbdxtools/commit/15b905cce98754103e33f96261ede9ef37475b6e

**Comment by drwelby** [comment]
Though I'm not sure how that fits with the current deprecation work.
