### ISSUE TITLE
Plot units don't make sense

### ISSUE THREAD

**Issue by drwelby** [DigitalGlobe/gbdxtools#409]
Plotting an image with dimensions results in an image that doesn't seem to have any relation to the units.

`image.plot(w=10, h=10)` 

Matplotlib plots are dimensioned in inches, and should plot at 72 dpi.

The above plot command will return an image around 600 pixels wide instead of 720.

If the plot is constructed manually we can confirm the plot size is 10x10 and the dpi is 72.

**Comment by drwelby** [comment]
This is due to the inline settings including `bbox_inches='tight'` 

The original figure is created at the correct dimension, but the figure has margins on all four sides, plus space for axes and labels on the left side and bottom.

`bbox_inches='tight'` essentially 'shrink-wraps' the image to remove extra white space and save storage space. This means the output image will be slightly smaller than the input dimensions indicate.

It might be possible to eliminate the margins and other unused space so the final dimensions are closer to what is expected.

**Comment by drwelby** [comment]
```python
import matplotlib as mpl
mpl.rcParams['savefig.pad_inches'] = 0
fig = plt.figure(figsize=(10,10), frameon=False)
ax = plt.Axes(fig, [0., 0., 1., 1.])
ax.get_xaxis().set_visible(False)
ax.get_yaxis().set_visible(False)
ax.set_title('IMAGE', fontsize=22)
fig.add_axes(ax)
plt.imshow(image.rgb(), interpolation='nearest', cmap=None)
plt.show(block=False)
```

Gets close, with an image 726 pixels wide. The question is whether this should be fixed, or whether an explanation in the docs is good enough.

**Comment by thesteve0** [comment]
I vote for explanation in the docs

**Comment by drwelby** [comment]
Adding this to the docs
