### ISSUE TITLE
Implement usage of __all__ in modules

### ISSUE THREAD

**Issue by rjpolackwich** [DigitalGlobe/gbdxtools#420]
## GBDXTools New Issue

Please provide some background information:
This library is coupled very tightly to DigitalGlobe Notebooks, where packages are baked into interactive envs, and provides the main image access/methods for users there. This means that API changes that are breaking will have the effect of invalidating previously "working" notebooks written in earlier versions when application docker images are updated. To ease the pain of notebook users (as well as us core gbdxtools developers), we should begin to take steps that will allow us to 1) make our API more well defined (what exact functiond, methods, mods are relevant for the API we choose to support robustly w.r.t. to users? The answer to this should likely be based developer opinions and empirical user behavior (available in notebooks) , so that we can 2)   issue deprecation warnings and timeframes in our changelog and release notes as appropriate regarding this API, and 3) introduce patterns that will make it easy to do 2).

One first step to something like this would be to define __all__ for modules, so that we can more easily do things like automatically wrap deprecations notices at the module level.

### GBDX Account Tier

* [ ] Community (Free)
* [ ] Notebooks Only
* [ ] GBDX Starter
* [ ] GBDX Enterprise
* [x] [other, please clarify]

### GBDXTools Version

Run `pip show gbdxtools` in a terminal or `!pip show gbdxtools` in a Jupyter notebook cell

[ 0.15.6 ]

### Python Version

* [ ] 2
* [ ] 3

### Environment

* [ ] GBDX Notebooks
* [ ] Local

[ If local, please provide more information about your local Python environment. For example, which Python executable - system or Anaconda? ]

### Description

[Description of the bug or feature]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Example

```
# Provide an example that reproduces the problem
image = CatalogImage()
print image.ntiles()
```

**Comment by rjpolackwich** [comment]
Take a look at twisted's [deprecation module](https://github.com/twisted/twisted/blob/5c1777777f85aaf799c2269f9f5dddcf0d59803e/src/twisted/python/deprecate.py). Would be awesome to implement something like this for gbdxtools.

**Comment by chelm** [comment]
Im surprised that there's not a generate deprecation decorator type lib available. That twisted module looks perfect for our use case

**Comment by rjpolackwich** [comment]
There actually is some python package called deprecate or something like that. Going to close this since we have implemented some stuff for this in our deprecate mod
