### ISSUE TITLE
CatalogImage should have standard names for all bands

### ISSUE THREAD

**Issue by thesteve0** [DigitalGlobe/gbdxtools#425]
## GBDXTools New Issue

Please make it so that there are three spec types in catalogimage pan|ms|thermal that "do the right thing" under the hoods when instatiating the actual image type. For example, with landsat8 the user should be able to say spec=pan just like they do with WV04, not needing to know that a landsatImage really needs "panchromatic"

**Comment by chelm** [comment]
So for wv04 and other sensors the keyword is actually `band_type=pan|MS`. I think for the classes where we use `spec=` it should just be converted to be `band_type`.

**Comment by chelm** [comment]
landsat and ikonos will support band_type="MS|Pan|thermal" in the next release

**Comment by thesteve0** [comment]
make it so - I was mostly writing this as a reminder
