### ISSUE TITLE
pansharpen on catalogimage should work for all supported satellites

### ISSUE THREAD

**Issue by thesteve0** [DigitalGlobe/gbdxtools#428]
Pansharpen=true should work for all supported satellites

It needs to be implemented on
Landsat8
Ikonos

Unknown 
Sentinel2 since we no longer even serve it through GBDX until the S3 situation is fixed

It works on 
WV02
WV03
WV04

It needs to be doc'ed that is not available for 
WV01

Notebooks do not expose Geoeye and quickbird in the search interface but they are available to anyone with a paid account. These are a lower priority.

**Comment by chelm** [comment]
Hey @drwelby what do you think about handling this? Its a matter of just augmenting the RDA graphs that get built when `pansharpen=True`

**Comment by chelm** [comment]
This rda graph shows how it would look for Landsat: 5a02ce1498e0b6dceafbcb316e5beff67d37a6eb2283275d5f5c69f55215e1f3

and its rather straightforward

**Comment by thesteve0** [comment]
@drwelby I think @chelm said you should take this one. This is high priority for me as it is holding up finishing the 3rd tutorial
