### ISSUE TITLE
warp is broken

### ISSUE THREAD

**Issue by rjpolackwich** [DigitalGlobe/gbdxtools#435]
## GBDXTools New Issue

Please provide some background information:

### GBDX Username

[your gbdx username]

### GBDX Account Tier

* [ ] Community (Free)
* [ ] Notebooks Only
* [ ] GBDX Starter
* [ ] GBDX Enterprise
* [ ] [other, please clarify]

### GBDXTools Version

Run `pip show gbdxtools` in a terminal or `!pip show gbdxtools` in a Jupyter notebook cell

[ 0.15.6 ]

### Python Version

* [x] 2
* [x] 3

### Environment

* [ ] GBDX Notebooks
* [ ] Local

[ If local, please provide more information about your local Python environment. For example, which Python executable - system or Anaconda? ]

### Description

[Description of the bug or feature]

### Expected behavior:

```
warped = image.warp(dem=0)
warped.compute()
```

### Actual behavior:
`TypeError: unhashable type: 'IdahoImage'`

[What actually happened]

### Example

```
# Provide an example that reproduces the problem

```

**Comment by drwelby** [comment]
Removing it for now in 8cb0de9fd18bd5ea1df8c03acbf2ca79c48b0449
