### ISSUE TITLE
Please add BaseLayerMatching to Browse Imagery as an rda.geobigdata.io Operator

### ISSUE THREAD

**Issue by MLGTimMLG** [DigitalGlobe/gbdxtools#437]
The Benefits would be:
-Saving GeoTiff with BaseLayerMatching with the .geotiff()
-Viewing blm as preview

As of now, that would be it. Those were just my issues.

**Comment by chelm** [comment]
Hi @MLGTimMLG We actually have recently added this, but also just realized that the browse image service we used for the work was just deprecated. We'll produce a new release with BLM on browse fixed soon. 

The geotiff method is bit tricky and right we support a `spec='rgb'` flag to the geotiff method, but i dont think that uses the browse. Will look into blm on those this week.

**Comment by MLGTimMLG** [comment]
Thank you for the quick response @chelm.
But I couldn't find it on rda.geobigdata.io.
![aaaa](https://user-images.githubusercontent.com/42335677/44114104-79998e4c-a00a-11e8-9063-514520c70d50.PNG)

**Comment by chelm** [comment]
Ahh now i actually read the title here. I dont this is the best place to request an RDA operator. You'll need to contact gbdx-support i think.

**Comment by chelm** [comment]
But on the other hand you do really need an RDA Op? Does doing this in gbdxtools on the client make any difference to having the server support it?

**Comment by MLGTimMLG** [comment]
Thanks for the tip! I think it makes things like plotting and geotiffing
easier.

2018-08-16 21:23 GMT+02:00 Christopher Helm <notifications@github.com>:
