### ISSUE TITLE
catalog.search returning 'HTTPError: 400 Client Error'

### ISSUE THREAD

**Issue by joshwapiano** [DigitalGlobe/gbdxtools#439]
## GBDXTools New Issue

Please provide some background information:
Hi,

I've been having issues searching the Digital Globe catalog for imagery metadata using gbdx.catalog. I've simplified the code I'm running in the relevant section below.

I've tried other methods for gbdx.catalog, such as:

record = gbdx.catalog.get('1050410011360700')
record

The above returns the expected result, as does CatalogImage (with actual imagery being displayed too) and so I am quite confident my auth details are correct, but I'm not sure what else to try to fix this issue.  Is it possible the url quoted above needs to be changed?

Many thanks for your help

Josh Stephenson

### GBDX Username
jsteph06@mail.bbk.ac.uk

### GBDX Account Tier
 GBDX Enterprise

### GBDXTools Version
Name: gbdxtools
Version: 0.15.11

### Python Version
3

### Environment
Local

Anaconda using the Conda install

### Description

HTTPError: 400 Client Error: Bad Request for url: https://geobigdata.io/catalog/v2/search

### Expected behavior:

catalog imagery metadata

### Actual behavior:

The following error:
```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-21-2e763a4390c4> in <module>()
      7 filt_eg = ["(sensorPlatformName = 'WORLDVIEW03' OR sensorPlatformName = 'WORLDVIEW04')", "cloudCover < 10"]
      8 gbdx = Interface()
----> 9 results = gbdx.catalog.search(searchAreaWkt = aoi, filters = filt_eg)

~/anaconda3/envs/senHubEnv/lib/python3.5/site-packages/gbdxtools/catalog.py in search(self, searchAreaWkt, filters, startDate, endDate, types)
    242         headers = {'Content-Type':'application/json'}
    243         r = self.gbdx_connection.post(url, headers=headers, data=json.dumps(postdata))
--> 244         r.raise_for_status()
    245         results = r.json()['results']
    246 

~/anaconda3/envs/senHubEnv/lib/python3.5/site-packages/requests/models.py in raise_for_status(self)
    937 
    938         if http_error_msg:
--> 939             raise HTTPError(http_error_msg, response=self)
    940 
    941     def close(self):

HTTPError: 400 Client Error: Bad Request for url: https://geobigdata.io/catalog/v2/search
```

I've followed the url separately in a browser and arrive at a JSON tab stating '{"message":"Missing Authentication Token"}'

There is also a 'Headers' tab with the following information:

```
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 42
Content-Type: application/json
Date: Tue, 14 Aug 2018 19:45:50 GMT
Via: kong/0.10.3
X-Amz-Cf-Id: 
X-Cache: Error from cloudfront
X-Kong-Proxy-Latency: 0
X-Kong-Upstream-Latency: 19
x-amz-apigw-id: LoSgVG72oAMFbyw=
x-amzn-ErrorType: MissingAuthenticationTokenException
x-amzn-RequestId:

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.5
Connection: keep-alive
Cookie: GBDX_Pendo_id=
Host: geobigdata.io
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0
```

### Example

```python
from gbdxtools import catalog
from gbdxtools import Interface
from shapely.geometry import box

bbox = [-246.239619,22.256492,-246.186319,22.312482]
aoi = box(*bbox).wkt
filt_eg = ["(sensorPlatformName = 'WORLDVIEW03' OR sensorPlatformName = 'WORLDVIEW04')", "cloudCover < 10"]
gbdx = Interface()
results = gbdx.catalog.search(searchAreaWkt = aoi, filters = filt_eg)
```

**Comment by drwelby** [comment]
Could you double-check your **bbox** and try again? `-246.239619` isn't a valid WGS84 coordinate.

**Comment by joshwapiano** [comment]
Thanks @drwelby, this solved the issue, and is returning some results now that I've changed the sensorPlatformName arguments to `'WORLDVIEW03_VNIR' OR 'WORLDVIEW03_SWIR'`.

I was using the tool found at https://tools.geofabrik.de/calc/, which it appears gives spurious results at times. Would it be worth adding some exception handling so that a more intuitive error is returned in this scenario?

**Comment by drwelby** [comment]
I'll check with the Catalog team to see if a better error message can be returned with an invalid bounding box.
