### ISSUE TITLE
s3.download is not working and throwing an error

### ISSUE THREAD

**Issue by loominator1970** [DigitalGlobe/gbdxtools#440]
## GBDXTools New Issue
Yes, this is new issue

Please provide some background information:
Hello,
 

A customer made me aware of an error he found using the s3.download function.  I was able to recreate the same error.  I am using gbdxtools v 0.15.7
 

### GBDX Username
dloomis@digitalglobe.com

### GBDX Account Tier

* [ ] Community (Free)
* [ ] Notebooks Only
* [ ] GBDX Starter
* [ X ] GBDX Enterprise
* [ ] [other, please clarify]

### GBDXTools Version
[ 0.15.7 ]

### Python Version

* [x ] 2
* [ ] 3

### Environment

* [ ] GBDX Notebooks
* [x ] Local

I have created a v-env using anaconda.  Its a Mac. I'm pretty sure the customer is using windows, but I'm not sure of the version of gbdxtools they are running

[ If local, please provide more information about your local Python environment. For example, which Python executable - system or Anaconda? ]

### Description

Code:
 

from gbdxtools import Interface
gbdx = Interface()
gbdx.s3.download(“DIRECTORY_IN_MY_BUCKET/FILE.TXT”,”/Users/dloomis/Downloads”)
 

Error:
 

Traceback (most recent call last):
  File "download_gbdx_data.py", line 18, in <module>
    gbdx.s3.download("s3://gbd-customer-data/58600248-2927-4523-b44b-5fec3d278c09/dloomis/alli/flood-water/shapefile/flood_vectors.prj","/User/dloomis/Desktop/junk")
  File "/Users/dloomis/miniconda2/envs/pabst2/lib/python2.7/site-packages/gbdxtools/s3.py", line 90, in download
    for s3key in s3conn.list_objects(Bucket=bucket, Prefix=(prefix+'/'+location))['Contents']:
KeyError: 'Contents'

### Expected behavior:

It should download the file to my local env

### Actual behavior:

error in downloading (see above)

### Example

Code:
 

from gbdxtools import Interface
gbdx = Interface()
gbdx.s3.download(“DIRECTORY_IN_MY_BUCKET/FILE.TXT”,”/Users/dloomis/Downloads”)

**Comment by mgregor-oa** [comment]
Tried the same code with my local bucket in GBDX Notebooks and produced the same error.

**Comment by drwelby** [comment]
What `bucket` and `prefix` are shown in `gbdx.s3.info`?

**Comment by mgregor-oa** [comment]
I used 
`bucket = gbdx.s3.info['bucket']`
`prefix = gbdx.s3.info['prefix']`

**Comment by chelm** [comment]
(1) The `s3.download` method only gives you access to your bucket and prefix in gbdx. So you should not need even know the actual bucket/prefix from `gbdx.s3.info`. The `download` method appends your gbdx bucket/prefix automatically.   

(2) this `gbdx.s3.download(“DIRECTORY_IN_MY_BUCKET/FILE.TXT”,”/Users/dloomis/Downloads”)` should absolutely work. Assuming that the `dir/file.txt` do in fact exist. We've just added some logic to better handle and throw errors when the files do not exist. 

Can you provide us with your user bucket/prefix and the actual file you're trying to access?

**Comment by mgregor-oa** [comment]
I edited my test code based on your comments.  `gbdx.s3.download('path/to/file.filetype')`  That worked for me now removing the bucket and prefix from my path string.  

I did another test as well using Dave Loomis account.  When you make the `gbdx.s3.download('s3://%s/%s/dloomis/alli/flood-water/shapefile/flood_vectors.prj %(bucket,prefix))` it fails but when you do `gbdx.s3.download('dloomis/alli/flood-water/shapefile/flood_vectors.prj)` if works.

It appears that you can't put the bucket and prefix in the call.  Is that what you are saying?

**Comment by chelm** [comment]
@mgregor-oa yes that is the way it was designed. I think the outcome of this issue is that docs should be updated and this made extremely clear.

**Comment by mgregor-oa** [comment]
Agreed.  I will make a note for the next meeting.
