### ISSUE TITLE
Add attribute filters to the catalog.py "search_point" function

### ISSUE THREAD

**Issue by loominator1970** [DigitalGlobe/gbdxtools#45]
The catalog.py module does not give the user a way to search by attributes and spatial filter.  These fitlers should be added to give the user this ability just as they have the ability in the "search" function.

**Comment by nricklin** [comment]
Hey Dave, does this not already do what you want?

http://gbdxtools.readthedocs.io/en/latest/catalog_search.html#search-with-filters

**Comment by nricklin** [comment]
added in version 0.3.0
