### ISSUE TITLE
rda.geobigdata.io issue

### ISSUE THREAD

**Issue by MLGTimMLG** [DigitalGlobe/gbdxtools#462]
When trying to:
![issue1](https://user-images.githubusercontent.com/42335677/44617091-4ce06780-a85d-11e8-989d-7efecf696453.PNG)
:
![issue2](https://user-images.githubusercontent.com/42335677/44617106-76998e80-a85d-11e8-832c-a513dd1c8264.PNG)

**Comment by MLGTimMLG** [comment]
In GBDX Notebooks it works even with preview.

**Comment by chelm** [comment]
There's probably a better place to submit these issues. The RDA team wont see them here. Will try to find a better place, and let you know

**Comment by MLGTimMLG** [comment]
Thank you!

**Comment by chelm** [comment]
Ok i think the most direct path for issues regarding the RDA Graph Studio will be to email GBDX-Support@digitalglobe.com
