### ISSUE TITLE
WV04 defaults for NWDI bands are incorrect

### ISSUE THREAD

**Issue by drwelby** [DigitalGlobe/gbdxtools#475]
The NWDI bands for WV04 images are not defined in the class, so they fall back to WV03 bands which are [0,7]. This throws an error since there are only four bands in WV04 images.

The bands should be correctly defined, or should throw some kind of NotImplemented error if it's not appropriate to derive NWDI from the WV04 bands.

**Comment by drwelby** [comment]
Dave Loomis is testing WV04 NWDI results, waiting for feedback.

**Comment by drwelby** [comment]
Bands should be [1,3] if results are considered acceptable.

**Comment by chelm** [comment]
pushed
