### ISSUE TITLE
plot should allow a title

### ISSUE THREAD

**Issue by thesteve0** [DigitalGlobe/gbdxtools#510]
## GBDXTools New Issue

When I call CatalogImage.plot()  I want to be able to specify a title for the resulting image

**Comment by drwelby** [comment]
You can pass `title` and `fontsize`. This is missing from the docs, I'll add them in.

**Comment by chelm** [comment]
@drwelby is this done?

**Comment by chelm** [comment]
yup done: https://gbdxtools.readthedocs.io/en/latest/api_reference.html#gbdxtools.images.mixins.geo.CatalogImage.plot
