### ISSUE TITLE
Point in Polygon Test for records returned from search (no partial chips)

### ISSUE THREAD

**Issue by jbsetton** [DigitalGlobe/gbdxtools#532]
## GBDXTools Feature Enhancement

While attempting to evaluate the GBDX platform to query and chip imagery across several AOIs it became apparent that the Catalog Service returns all records that intersect with the search area. For uses requiring image chips that fully cover an AOI, a visual inspection or point in polygon test of image chip "footprints" is needed to ensure a valid chip is obtained.

### GBDX Username

jbiagio@settonfarms.com

### GBDX Account Tier

* [ ] Community (Free)
* [ ] Notebooks Only
* [ ] GBDX Starter
* [ ] GBDX Enterprise
* [x] Setton Farms Basic Eval

### GBDXTools Version

Run `pip show gbdxtools` in a terminal or `!pip show gbdxtools` in a Jupyter notebook cell

0.15.13

### Python Version

* [ ] 2
* [x] 3

### Environment

* [ ] GBDX Notebooks
* [x] Local

The Python used is an Anaconda environment with the following packages installed: 

affine                    2.2.1                      py_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
atomicwrites              1.2.1                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
blas                      1.0                         mkl
blinker                   1.4                        py_1    conda-forge
bokeh                     0.13.0                py36_1000    conda-forge
boost                     1.66.0              py36_vc14_1  [vc14]  conda-forge
boost-cpp                 1.66.0                   vc14_1  [vc14]  conda-forge
boto3                     1.9.21                     py_0    conda-forge
botocore                  1.12.23                    py_0    conda-forge
bumpversion               0.5.3                 py36_1000    conda-forge
ca-certificates           2018.03.07                    0
cachetools                2.1.0                      py_0    conda-forge
certifi                   2018.10.15               py36_0
cffi                      1.11.5          py36hfa6e2cd_1001    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                    py36_0
cligj                     0.5.0                    py36_0
cloudpickle               0.6.1                      py_0    conda-forge
colorama                  0.3.9                      py_1    conda-forge
configparser              3.5.0                 py36_1001    conda-forge
cryptography              2.3.1            py36h74b6da3_0    conda-forge
cryptography-vectors      2.3.1                 py36_1000    conda-forge
curl                      7.60.0                   vc14_0  [vc14]  conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1         py36hfa6e2cd_1001    conda-forge
dask                      0.19.4                     py_0    conda-forge
dask-core                 0.19.4                     py_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
distributed               1.23.3                py36_1000    conda-forge
docutils                  0.14                  py36_1001    conda-forge
ephem                     3.7.6.0         py36hfa6e2cd_1001    conda-forge
expat                     2.2.5                    vc14_0  [vc14]  conda-forge
fiona                     1.7.10           py36h5bf8d1d_0
freetype                  2.8.1                    vc14_0  [vc14]  conda-forge
freexl                    1.0.2                    vc14_2  [vc14]  conda-forge
future                    0.16.0                py36_1002    conda-forge
gbdx-auth                 0.4.0              pyh6bac6e9_0    digitalglobe
gbdxtools                 0.15.13            pyhbac1adf_0    digitalglobe
gdal                      2.2.4            py36h2fc6367_1    conda-forge
geos                      3.6.2                h9ef7328_2
geotiff                   1.4.2                    vc14_1  [vc14]  conda-forge
hdf4                      4.2.13                   vc14_0  [vc14]  conda-forge
hdf5                      1.10.1                   vc14_2  [vc14]  conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                     vc14_0  [vc14]  conda-forge
idna                      2.7                   py36_1002    conda-forge
imageio                   2.3.0                      py_1    conda-forge
intel-openmp              2019.0                      118
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9b                       vc14_2  [vc14]  conda-forge
kealib                    1.4.7                    vc14_4  [vc14]  conda-forge
kiwisolver                1.0.1           py36he980bc4_1002    conda-forge
krb5                      1.14.6                   vc14_0  [vc14]  conda-forge
libboost                  1.67.0               hd9e427e_4
libcurl                   7.61.1               h7602738_0
libgdal                   2.2.4                    vc14_5  [vc14]  conda-forge
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libkml                    1.3.0                he5f2a48_4
libnetcdf                 4.6.1                    vc14_2  [vc14]  conda-forge
libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
libpq                     9.6.3                    vc14_0  [vc14]  conda-forge
libspatialite             4.3.0a                  vc14_19  [vc14]  conda-forge
libssh2                   1.8.0             hc4dcbb0_1002    conda-forge
libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
libxml2                   2.9.5                    vc14_1  [vc14]  conda-forge
locket                    0.2.0                      py_2    conda-forge
markupsafe                1.0             py36hfa6e2cd_1001    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mercantile                1.0.4                      py_0    conda-forge
mkl                       2019.0                      118
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
more-itertools            4.3.0                 py36_1000    conda-forge
msgpack-python            0.5.6           py36he980bc4_1003    conda-forge
munch                     2.3.2                    py36_0
networkx                  2.2                        py_1    conda-forge
numpy                     1.15.2           py36ha559c80_0
numpy-base                1.15.2           py36h8128ebf_0
oauthlib                  2.1.0                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.0                    vc14_2  [vc14]  conda-forge
openssl                   1.0.2p               hfa6e2cd_0
packaging                 18.0                       py_0    conda-forge
pandas                    0.23.4          py36h830ac7b_1000    conda-forge
partd                     0.3.9                      py_0    conda-forge
pillow                    5.2.0                    py36_0    conda-forge
pip                       10.0.1                   py36_0
pluggy                    0.7.1                      py_0    conda-forge
proj4                     4.9.3                    vc14_5  [vc14]  conda-forge
psutil                    5.4.7           py36hfa6e2cd_1001    conda-forge
py                        1.7.0                      py_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pycurl                    7.43.0.2         py36h74b6da3_0
pyjwt                     1.6.4                      py_0    conda-forge
pyodbc                    4.0.24           py36h6538335_0
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.2.2                      py_0    conda-forge
pyproj                    1.9.5.1         py36haf3c679_1005    conda-forge
pyqt                      5.6.0            py36h764d66f_7    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
pytest                    3.8.2                 py36_1000    conda-forge
pytest-runner             4.2                        py_1    conda-forge
python                    3.6.6                hea74fb7_0
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pywavelets                1.0.1           py36h452e1ab_1000    conda-forge
pyyaml                    3.13            py36hfa6e2cd_1001    conda-forge
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
rasterio                  0.36.0           py36hb8ea33a_1
requests                  2.19.1                py36_1001    conda-forge
requests-futures          0.9.7                    py36_1    conda-forge
requests-oauthlib         1.0.0                      py_1    conda-forge
s3transfer                0.1.13                py36_1001    conda-forge
scikit-image              0.14.1          py36h6538335_1000    conda-forge
scipy                     1.1.0            py36h4f6bf74_1
setuptools                40.4.3                   py36_0
shapely                   1.6.4            py36hc90234e_0
sip                       4.18.1           py36h6538335_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
snuggs                    1.4.2                    py36_0
sortedcontainers          2.0.5                      py_0    conda-forge
sqlite                    3.20.1                   vc14_2  [vc14]  conda-forge
tblib                     1.3.2                      py_1    conda-forge
tk                        8.6.8                    vc14_0  [vc14]  conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1           py36hfa6e2cd_1000    conda-forge
urllib3                   1.23                  py36_1001    conda-forge
vc                        14                            0    conda-forge
vcrpy                     2.0.1                 py36_1000    conda-forge
vs2015_runtime            14.15.26706          h3a45250_0
wheel                     0.32.1                   py36_0
win_inet_pton             1.0.1                 py36_1002    conda-forge
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.10.11         py36hfa6e2cd_1001    conda-forge
xerces-c                  3.2.0                    vc14_0  [vc14]  conda-forge
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                    vc14_0  [vc14]  conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

### Description
As an option it would be nice if a "point in polygon" test could be performed wherein the "points" (corners) of a search area could be iterated through the "footprint" of the returned records, to cull out the ones that only partially cover the search area. Using something similar to shapely's "point in polygon" test, any corner returning "False" (that is, it is not in the polygon "footprint") would result in the record being ignored. This test could feasibly be leveraged as an added arguement to the catalog search. 

### Example
Please forgive the pedantic coding...
```
# Provide an example that reproduces the problem
from gbdxtools import Interface, CatalogImage
from gbdxtools.catalog import Catalog
from shapely.wkt import loads
from shapely.geometry import Point
import os

gbdx = Interface()

# Set search parameters for GBDX catalog search
filters = ["(sensorPlatformName = 'WORLDVIEW02' OR sensorPlatformName = 'WORLDVIEW03_VNIR')"]
results = gbdx.catalog.search(
        searchAreaWkt=wkt_string,
        startDate ="2017-11-01T00:00:00.000Z",
    	endDate= "2018-02-28T23:59:59.999Z",
        filters=filters
        )
```
wkt_string is returned from iterating through a list of AOIs (not shown).

```
# Get Catalog IDs from search
catalog_ids = [r['identifier'] for r in results]

print(len(catalog_ids))

# Create an empty dictionary to check for 'known good' image chips (those that completely cover aoi).
goodChips={}

aoipts = loads(wkt_string)  # Shapely WKT object from AOI string
aoiList = list(aoipts.exterior.coords)[:-1]  # Remove last point as wkt repeats first point as last

for i in range(len(catalog_ids)):
    imageId = catalog_ids[i]
    record = gbdx.catalog.get(imageId)
    footprint = record['properties']['footprintWkt']
    fp = loads(footprint)
    goodChips.update({imageId:(footprint, 'true')})

    # Point in Polygon Test  <-- Very important to check to see if image chip fully covers aoi
    for e in range(len(aoiList)):
        test = Point(aoiList[e])
        # print(test)

        # Try to iterate through test (aoi) points to see if they all reside in the fp (wkt object of image chip)
        if not fp.contains(Point(test)):
            # print(fp.contains(Point(test)))
            goodChips.update({imageId:(footprint,'false')})  # Create known 'good' dictionary for further processing
            break

# print(goodChips)
```

**Comment by drwelby** [comment]
Thank you for providing such a detailed feature request.

You are correct that currently GBDX Catalog searches only return intersecting images. We have asked the GBDX Catalog team to see if they can expand this to include **contains**, **within**, and **disjoint** searches. When the functionality is exposed then we can add the option to GBDXTools.

In the meantime you can make the **contains** check code a little simpler:

```python
for imageId in catalog_ids:
    record = gbdx.catalog.get(imageId)
    footprint = record['properties']['footprintWkt']
    fp = loads(footprint)
    goodChips.update({imageId:(footprint, 'true')})
    if not fp.contains(loads(wkt_string)):
        goodChips.update({imageId:(footprint,'false')})
```

For a working example, please see:

https://notebooks.geobigdata.io/hub/notebooks/5bd340aaa5fd25524530dc20?tab=code

**Comment by jbsetton** [comment]
Thank you Marc.
Your code is far more elegant than mine!
I will revise on my end and continue to follow your progress as well as that of the GBDX Catalog team.
Thank you again.
Respectfully,

Jason Biagio | Geospatial Developer/Analyst | Setton Pistachio of Terra Bella, Inc. | 9370 Road 234, Terra Bella, CA 93270 | T 559.535.6050<tel:5595356050>
Visit us online SettonFarms.com<http://www.settonfarms.com/> | Follow us on Facebook<https://www.facebook.com/SettonFarmsPistachioChewyBites>

**Comment by chelm** [comment]
Going to close this for now as we cant really support it beyond what vector services can provide.
