### ISSUE TITLE
Error about ’gbdx.s3.upload‘

### ISSUE THREAD

**Issue by cookerman2011** [DigitalGlobe/gbdxtools#585]
When I run the following code：

```
from gbdxtools import Interface 
gbdx = Interface()
gbdx.s3.upload('new/1.tif')
```

No data returned in s3

**Comment by drwelby** [comment]
Confirming this problem. The workaround is:

```
from gbdxtools import Interface 
gbdx = Interface()
gbdx.s3.upload('new/1.tif', s3_path='1.tif') # or s3_path='new/1.tif' to mirror the subdirectory
```
Will fix in the next release.

**Comment by chelm** [comment]
A push for this and updated docs around s3.upload has been pushed and merged. Will be in release 0.16.3
