### ISSUE TITLE
s3 receiving bucket location inconsistent

### ISSUE THREAD

**Issue by yidongVSI** [DigitalGlobe/gbdxtools#60]
As I order images using their catalog id, I could check order status to obtain the image location on S3 bucket, like

```
gbdx.ordering.status(order_id)
[{u'acquisition_id': u'103001000C013F00',
u'location': u's3://receiving-dgcs-tdgplatform-com/055167650010_01_003',
u'state': u'delivered'}]
```

Once the order delivered, I am suppose to be able to get S3 location using `gbdx.catalog.get_data_location(catalog_id='103001000C013F00')`

However, sometimes the returned s3 locations is different from the one in order status, or `gbdx.catalog.get_data_location` returns None for newly ordered images even though the order status is delivered.

Is it possible because in `gbdx.catalog.get_data_location`, it uses v1 version of url '`url = 'https://geobigdata.io/catalog/v1/traverse`' ?

**Comment by nricklin** [comment]
As of version 0.6.2 you can now do:

``` python
gbdx.ordering.location(['103001000C013F00', 'cat_id2','cat_id3'])​
```

The inconsistency you see is due to data duplication in the catalog, since in some cases the data had been ordered more than once.   `gbdx.ordering.location`  is now the best way to find the s3 location of ordered data.

Hope that helps!
