### ISSUE TITLE
Feature info got lost after vector styling overhaul

### ISSUE THREAD

**Issue by drwelby** [DigitalGlobe/gbdxtools#611]
The update to vector styles no longer includes a click handler on features that displays the feature info. Can this be put back in?

**Comment by chelm** [comment]
I think so yes. I deliberately took it out as the implementation was done poorly. i'd like to bring it back, but done a bit cleaner, possibly with a kwarg flag to `map` and possibly a mouseover event instead of click.

**Comment by chelm** [comment]
added back
