### ISSUE TITLE
Preview doesn't work on DRA'ed images

### ISSUE THREAD

**Issue by drwelby** [DigitalGlobe/gbdxtools#621]
If a CatalogImage is created with `dra=True`, the `preview()` slippy map shows black or dark tiles. This is because `preview()` tries to apply its own DRA to get the pixel range to a displayable format and it overshoots or fails if the image already has been balanced.

The solution appears to be to skip the DRA step if it has already been applied.

See https://github.com/DigitalGlobe/gbdxtools/commit/44c05d489187f7ed1f15e096c8cd1645d08ea544

**Comment by drwelby** [comment]
We should probably store in the image object whether DRA is applied so other methods like `plot()` don't double-adjust.

**Comment by chelm** [comment]
This is merged into dev
