### ISSUE TITLE
ShareDict deprecation in Dask

### ISSUE THREAD

**Issue by drwelby** [DigitalGlobe/gbdxtools#630]
`UserWarning: ShareDict has been deprecated in favor of HighLevelGraph and will be removed in future versions`

Used only in meta.py

**Comment by chelm** [comment]
Any info on how to reproduce this?

**Comment by drwelby** [comment]
@msmith303 was getting it in E2E tests

**Comment by rjpolackwich** [comment]
https://github.com/DigitalGlobe/gbdxtools/pull/639
