### ISSUE TITLE
Vector maps with images lock up in published GBDX Notebooks

### ISSUE THREAD

**Issue by drwelby** [DigitalGlobe/gbdxtools#641]
See https://notebooks.geobigdata.io/hub/notebooks/6j6ih2ecwaor5v24z810?tab=code

The original Jupyter notebook cached the background image in `blob:https://notebooks.geobigdata.io/...`, the published notebook sees that as `blob:null/...` and throws a CORS error, which locks up the map.

Tracking here, addressed internally as RPT-3193.

**Comment by chelm** [comment]
interesting though that in devtools it does fetch the base64 uri.

**Comment by drwelby** [comment]
yeah, it's very weird and I have no idea who to point fingers at.

**Comment by drwelby** [comment]
Works in Safari - may be a Chrome bug?
