### ISSUE TITLE
How can one download files using s3browser?

### ISSUE THREAD

**Issue by d3netxer** [DigitalGlobe/gbdxtools#642]
Using Python I am able to print out the S3 information with gbdx.s3.info. Then in s3browser I create a new account and input my S3_secret_key and S3_accesskey. Then S3 gives the following server response: "InvalidAccessKeyID: The AWS Access Key Id you provided does not exist in our records"

**Comment by chelm** [comment]
I'm unclear about how s3Browser works so I'm not sure how to answer this with regards to "gbdxtools". 

The credentials in `gbdx.s3.info` are credentials that will only give you access to data within the `bucket` and `prefix` from the same `gbdx.s3.info`. 

You can download files with `gbdx.s3.download` as well.

**Comment by chelm** [comment]
@d3netxer are you using? http://s3browser.geobigdata.io/login.html

**Comment by chelm** [comment]
The creds you receive from gbdxtools/gbdx are temporary creds and will only work when logged in GBDX's s3Browser or from gbdxtools. 

Going to close this.
