### ISSUE TITLE
Wildcards not working in gbdxtools [ ref:_00D61HtDy._50061VsDwA:ref ]

### ISSUE THREAD

**Issue by GBDX-Support** [DigitalGlobe/gbdxtools#678]
## GBDXTools New Issue

I am trying to do a catalog search with filters and a wildcard, but I can't duplicated the api call with gbdxtools.

### GBDX Username

matthew.gregor@digitalglobe.com

### GBDX Account Tier

* [ ] Community (Free)
* [ ] Notebooks Only
* [ ] GBDX Starter
* [ * ] GBDX Enterprise
* [ ] [other, please clarify]

### GBDXTools Version

Run `pip show gbdxtools` in a terminal or `!pip show gbdxtools` in a Jupyter notebook cell

[ 0.16.5 ]

### Python Version

* [ ] 2
* [ * ] 3

### Environment

* [ * ] GBDX Notebooks
* [ ] Local

[ If local, please provide more information about your local Python environment. For example, which Python executable - system or Anaconda? ]

### Description

Running a catalog search with gbdxtools return no results for the following code:
filters = ["sensorPlatformName LIKE 'QUICKBIRD%'"]
results = gbdx.catalog.search(filters=filters)
print(len(results))

### Expected behavior:

len(results)>0

### Actual behavior:

len(results)==0

### Example

```
from gbdxtools import Interface
gbdx = Interface()
filters = ["sensorPlatformName LIKE 'QUICKBIRD%'"]
results = gbdx.catalog.search(filters=filters)
print(len(results))
```
[ ref:_00D61HtDy._50061VsDwA:ref ]

**Comment by drwelby** [comment]
```
{
    	"searchAreaWkt": "POLYGON ((-105.35202026367188 39.48113956424843, -105.35202026367188 40.044848254075546, -104.65988159179688 40.044848254075546, -104.65988159179688 39.48113956424843, -105.35202026367188 39.48113956424843))",
    	"filters": ["sensorPlatformName LIKE 'QUICKBIRD%'"]
    }
```

This also returns 0 results against the V2 API, we will have to check with the catalog team why that field doesn't support LIKE queries.

**Comment by drwelby** [comment]
This appears to be entirely on the Catalog side and not a problem introduced by gbdxtools.
