### ISSUE TITLE
GBDX running locally request error

### ISSUE THREAD

**Issue by barrybrianbarrios** [DigitalGlobe/gbdxtools#699]
## GBDXTools New Issue

Please provide some background information:

### GBDX Username
barry.b.barrios@raytheon.com

### GBDX Account Tier
GBDX Enterprise

### GBDXTools Version

Run `pip show gbdxtools` in a terminal or `!pip show gbdxtools` in a Jupyter notebook cell
[ 0.16.5 ]

### Python Version
Python 3.6.6
### Environment
Local

[ If local, please provide more information about your local Python environment. For example, which Python executable - system or Anaconda? ]
System

### Description
I can authenticate but can't plot image from catalog locally

[Description of the bug or feature]
# For compatibility with Python 3.3+
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='vector.geobigdata.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001E92646D208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
### Expected behavior:

[What you expected to happen]
I expect to be able to plot an image from the catalog locally at work. We have a firewall so things may get blocked but there should be a way to get it to work still.

### Actual behavior:
Getting error messages
[What actually happened]
I get a connection error
### Example

```
# Provide an example that reproduces the problem
from gbdxtools import Interface
from gbdxtools import CatalogImage, Interface
gbdx = Interface()
catalog_id = '104001000D835700'
bbox = [112.889, 9.55, 112.912, 9.563]
image = CatalogImage(catalog_id, band_type="MS", pansharpen=True, bbox=bbox)

```

**Comment by chelm** [comment]
@barrybrianbarrios Do you get the same error when running this code? 
```python
from gbdxtools import Interface
gbdx = Interface()

r = gbdx.gbdx_connection.get('https://vector.geobigdata.io/insight-vector/api/vectors/query/items')
print(r.content)
```

**Comment by chelm** [comment]
Could this be related to any internal proxies or firewalls?

**Comment by barrybrianbarrios** [comment]
I get this error:
 r = gbdx.gbdx_connection.get('https://vector.geobigdata.io/insight-vector/api/vectors/query/items')
Traceback (most recent call last):
.......
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='vector.geobigdata.io', port=443): Max retries exceeded with url: /insight-vector/api/vectors/query/items (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000203FB40BC18>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
>>> print(r.content)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'r' is not defined

**Comment by chelm** [comment]
This really feels like a network issue and not really directly anything that gbdxtools is doing. Can you try this one a different network?

**Comment by barrybrianbarrios** [comment]
yeah we have a proxy and firewall but was curious if there's a workaround solution to get through it using another method. It runs fine at home on my home network, but will like this to run at work.

**Comment by barrybrianbarrios** [comment]
yeah we have a proxy and firewall but was curious if there's a workaround solution to get through it using another method. It runs fine at home on my home network, but will like this to run at work.

**Comment by drwelby** [comment]
Closing, GBDXtools has no functionality to change network behavior.
