### ISSUE TITLE
Monitor STDOUT on a running task

### ISSUE THREAD

**Issue by loominator1970** [DigitalGlobe/gbdxtools#71]
We have a customer that has a requested to have a gbdxtools method that shows the 'stdout' on any given task.  It could probably just be the stdout for every task in the workflow.  Something like "workflow.get_task_stdout" would probably work just fine.

**Comment by nricklin** [comment]
I think I just came to the same conclusion in #72 .  

I'm going to close this issue because it's a duplicate.
