### ISSUE TITLE
Access to task id enhancement

### ISSUE THREAD

**Issue by Mattpwinchester** [DigitalGlobe/gbdxtools#72]
In order to pull data from the stdout of a docker container running on GBDX, you currently need both the workflow ID and the task ID. Both are dynamically generated at runtime. However, one is easy to find (workflow ID) and the other not so much. If there was a single function to call to grab the 'id' of a task inside of a given workflow this would make writing a script to check the details of the running status of a docker container on GBDX significantly easier. 

I requested for David Loomis to collaborate with me on this effort.

**Comment by nricklin** [comment]
so something like this?

``` python
task1 = gbdx.Task('Task1', inputs = ...)
task2 = gbdx.Task('Task2', inputs = ...)
workflow = gbdx.Workflow([task1, task2])
workflow.execute()

# get task stdout
print task1.stdout
```

I can foresee some problems with that, if you use the task in 2 workflows for example.  

Maybe: 

``` python
print workflow.get_stdout(task1)
# or
print workflow.tasks.task1.stdout
```

or maybe just

``` python
workflow.stdout
```

and it prints out a dict of all the stdout from all tasks.

I'm leaning toward this last one.

**Comment by Mattpwinchester** [comment]
How about when we startup a workflow with a list of N tasks, it assigns each task an ID in the workflow? Ultimately, I need a means to say "build a workflow and give me the ID of a task given a specific task name". That way, I can use the API for loading JSON with both a) the workflow ID and b) the task ID, which will allow me to send that in a request to the workflow/stdout & stderr endpoint. 

Currently, I have to get this information by hand using the web interface. If I want to automate ordering and processing of GBDX data, I need an automated means to track, manage, record, and document results for each workflow being issued.

**Comment by nricklin** [comment]
@Mattpwinchester   can you sketch out in pseudo python code what you want to do?  There's a lot in there, and I don't want to misinterpret.

**Comment by Mattpwinchester** [comment]
Sure thing,

The idea behind this is that in order to hit the GBDX API endpoint to collect stdout/stderr from a docker container on the GBDX platform I need to have both:

1) The Task ID of the task running the container 
2) The workflow ID of the workflow that issued the task from 1)

Currently, it appears that I can only collect the workflow ID through issuing the workflow with:

wid = workflow.execute()

I want to be able to somehow use the workflow ID to find the task ID or maybe return a list of task IDs to me along with the workflow ID upon workflow execution. I assume that the IDs are generated through a GBDX connection Issuing it a UID for workflow ID to ensure no shadowing occurs. 

Honestly, being this would be the most convenient:

do_something_task, task_id = gbdx.Task("P=NP", data=math.outputs.value)

However, if I need to somehow use the workflowID to grab the list of tasks and parse them for the one I am looking for, I will figure out a means to get it to work.

**Comment by nricklin** [comment]
Ok cool.  that may be pretty simple.  

Unfortunately task_ids are not known until the WF is executed.  So we have to execute first, then access the task Ids.

I could see:
```python
wf = gbdx.Workflow([task1, task2])
wf_id = wf.execute()
task_ids = wf.task_ids
```
or something similar.

But what you're really after is stdout and sderr anyway, right?  So looking at this again, ```workflow.stdout``` providing a list of tasks with their stdout may be reasonable too.

**Comment by nricklin** [comment]
Stuff implemented that adds the requested functionality.

See:  http://gbdxtools.readthedocs.io/en/latest/running_workflows.html#workflow-stdout-and-stderr
and: http://gbdxtools.readthedocs.io/en/latest/running_workflows.html#task-ids-in-a-running-workflow
