### ISSUE TITLE
Fix RTD docs

### ISSUE THREAD

**Issue by drwelby** [DigitalGlobe/gbdxtools#724]
- PDF generation is ugly
- Remove Kostas as maintainer
- Fix branding stuff
- check ePub version

@chelm or @kostasthebarbarian can you add me as a maintainer in RTD?

**Comment by chelm** [comment]
You betcha, all done. https://readthedocs.org/projects/gbdxtools/

**Comment by drwelby** [comment]
Turned off PDF and ePub generation in RTD since they have never been build targets in development.
