### ISSUE TITLE
v 0.16.7 release

### ISSUE THREAD

**Issue by drwelby** [DigitalGlobe/gbdxtools#749]
v 0.16.7 will be a minor release to update dependencies and few bugs and will be the last in the 0.16 series.

### bugfixes/changes:

- #676
- #727 
- #723 

### Dependency problems:

- scipy.misc for imread has been moved to imageio, need to check that import in tmsimage.py
- pycurl install is problematic on Mac due to` __main__.ConfigurationError: Curl is configured to use SSL, but we have not been able to determine which SSL backend it is using. Please see PycURL documentation for how to specify the SSL backend manually.` Need fix or warning in docs.

v 0.17.0 will start the RDA graph deprecation process.

**Comment by drwelby** [comment]
v0.16.7 is now in PyPi

**Comment by shexiaogui** [comment]
which python version is compatible with 0.16.7? python 3.6 or 3.7?

**Comment by drwelby** [comment]
@shexiaogui 3.6

**Comment by shexiaogui** [comment]
Another question: what is the dask and scipy version in release 0.16.7? I have dask 2.3.0 installed. and it seems not working.

**Comment by drwelby** [comment]
I believe 1.2.2 works. It has not been tested with any of the 2.x.x versions of Dask.
