### ISSUE TITLE
multiplex input with unknown number of inputs

### ISSUE THREAD

**Issue by yidongVSI** [DigitalGlobe/gbdxtools#76]
In the test cases or documentations, I see a multiplex inputs generally defined as
`task = self.gbdx.Task('gdal-cli-multiplex', data1='asdf', data2='fdsa')`
or 
`task = self.gbdx.Task('gdal-cli-multiplex')`
`task.inputs.data1.value = 'asdf'`
`task.inputs.data2.value = 'fdsa'`
where `data` is a multiplex input.

In my case, I don't know exact number of `data` I have, so I can not explicitly sepcify `data1=..., data2=..., data3=...`.  Before, I solve this by defining my task/workflow as dictionary, then submit the workflow via workflow module `gbdx.workflow.launch(payload)` or `gbdx.workflow.launch_batch_workflow(payload)`.

This workflow module is however not working any more in version 0.7.2 (relate to issue #52 ).  More specifically, `gbdx.workflow.launch(payload)` still works but `gbdx.workflow.launch_batch_workflow(payload)` failed...

Is there any way to do this using `gbdxtools/simpleworkflows.py`

Thanks

**Comment by yidongVSI** [comment]
FYI, Problem solved... 
Turns out the format of port descriptor is changed for batch input.  previous format is 
`"name": "data",`
`"value": "$batch_value:batch_value_name"`
new format is
`"name": "data",`
`"value": "{{batch_value_name}}"`

and this update leads to my failure of using `gbdx.workflow.launch_batch_workflow(payload)`

The question I have now is whether [https://github.com/DigitalGlobe/gbdxtools/blob/master/gbdxtools/workflow.py#L180](url) will be deprecated sometime in future.  If so, then how to use simpleworkflow to submit jobs via port descriptor format, like before

**Comment by nricklin** [comment]
Good catch on the change.  We made sure that the change would not affect the simpleworkflows interface but did not take as much care with the raw json interface.

Probably we will not deprecate the raw json interfaces because they are used by the simpleworkflows objects.

Let me see if I understand your problem:  You have a data-defined number of multiplex inputs, so you'd like to specify them as data somehow, rather than "hard code" arguments you may not use?

**Comment by nricklin** [comment]
It's not very clean, but would doing this help?

```python
task.inputs.__setattr__('data2', 'value')
```
This is equivalent to
```python
task.inputs.data2 = 'value'
```

but maybe a bit more scriptable.

**Comment by yidongVSI** [comment]
Thanks for the comments and clarification.  Yes, __setattr__ will definitely help for my case where number of inputs is unknown at the begining.  

Glad that the json interface won't be removed.  But I couldn't find an example/test/documentation that illustrates how to use json interface in simpleworkflow case.  It would be great if there is something I can follow such that I could modify all my GBDX tasks using simpleworkflow

Thanks again for all the suggestion

**Comment by nricklin** [comment]
Json and the simpleworkflow construct are mutually exclusive.  All the simpleworkflow construct is doing is helping create the correct json in a scriptable way.  If you've got your own gear building out the json, that's fine too :)

I'm going to close this now.  If you can come up with some syntax in a way that you'd like to script for multiple unknown multiplex inputs, we can add it to gbdxtools.  The hardest part is figuring out the way we want it to be.
