### ISSUE TITLE
Add task_id to workflow.events

### ISSUE THREAD

**Issue by loominator1970** [DigitalGlobe/gbdxtools#77]
We have a customer that would like to access the task_id from the workflow.events method.  Its current configuration is like this:

{u'task': u'CarDetection_AOP_C_276383d1-1059-4254-9c22-c8b4d9825461', u'timestamp': u'2016-11-30T13:24:09.088490+00:00', u'when': u'2 days ago', u'note': u'instance_id: i-c92fa74a', u'state': u'pending', u'event': u'scheduled'}

Can you add task["id"] to the dictionary?

Dave

**Comment by Mattpwinchester** [comment]
Reference: https://github.com/DigitalGlobe/gbdxtools/issues/72

**Comment by nricklin** [comment]
seems reasonable.  I think we should add it to the API (the workflow.events method is a direct representation of what comes out of the api)

**Comment by nricklin** [comment]
This has been added, so will roll out in one of our next deploys.

**Comment by nricklin** [comment]
I just verified that the field is available as "task_id".  Example:
```
task["task_id"]
```
