### ISSUE TITLE
import fails with ImportError: cannot import name 'imread'

### ISSUE THREAD

**Issue by joemcglinchy** [DigitalGlobe/gbdxtools#771]
## GBDXTools New Issue

Please provide some background information:

### GBDX Username

joseph.mcglinchy@colorado.edu

### GBDX Account Tier

* [ ] Community (Free)
* [ ] Notebooks Only
* [ ] GBDX Starter
* [x ] GBDX Enterprise
* [ ] [other, please clarify]

### GBDXTools Version

Run `pip show gbdxtools` in a terminal or `!pip show gbdxtools` in a Jupyter notebook cell

[ 0.16.5 ]

### Python Version

* [ ] 2
* [x ] 3

### Environment

* [ ] GBDX Notebooks
* [x ] Local

Anaconda3, python 3.6.7, Ubuntu 18.04.2

### Description
'import gbdxtools' fails with:
/home/joemcglinchy/anaconda3/envs/eapy_torch/lib/python3.6/site-packages/gbdxtools/images/meta.py:21: UserWarning: ShareDict has been deprecated in favor of HighLevelGraph and will be removed in future versions
  from dask import sharedict, optimization
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joemcglinchy/anaconda3/envs/eapy_torch/lib/python3.6/site-packages/gbdxtools/__init__.py", line 10, in <module>
    from gbdxtools.images.tms_image import TmsImage
  File "/home/joemcglinchy/anaconda3/envs/eapy_torch/lib/python3.6/site-packages/gbdxtools/images/tms_image.py", line 20, in <module>
    from scipy.misc import imread
ImportError: cannot import name 'imread'

### Expected behavior:

successful import

### Actual behavior:

failed import

### Example

see above

**Comment by joemcglinchy** [comment]
installed using `conda install -c conda-forge -c digitalglobe gbdxtools`

**Comment by drwelby** [comment]
Newer versions of scipy dropped `imread`. You can get around this by installing an older version:

`conda install -c conda-forge -c digitalglobe scipy=1.0.0 gbdxtools`

We have a new release of GBDXtools almost ready that catches up all the dependencies.

**Comment by anthony-ct** [comment]
How is the new release of gbdxtools coming along?

**Comment by drwelby** [comment]
It's temporarily on pause.

**Comment by drwelby** [comment]
addressed in https://github.com/DigitalGlobe/gbdxtools/commit/5c09217c2cf50da183f768178955008f31ad99cd
