### ISSUE TITLE
Sentinel1 images ignore polarization argumenr

### ISSUE THREAD

**Issue by drwelby** [DigitalGlobe/gbdxtools#779]
Sentinel1 images ignore the `polarization` argument because the class is using the Sentinel2 driver by mistake. Unless the argument is specified in the driver's options it is skipped

Workaround:

```
from gbdxtools.rda.interface import RDA
from gbdxtools.images.rda_image import RDAImage
rda = RDA()
op = rda.Sentinel1Read(SentinelId='S1A_EW_GRDM_1SSH_20161120T103648_20161120T103752_014024_0169BC_F97C', sentinel1Polarization='HH')
img = RDAImage(op)

**Comment by drwelby** [comment]
Need to check templates

**Comment by mchaudry** [comment]
Fixed in https://github.com/DigitalGlobe/gbdxtools/pull/810
