### ISSUE TITLE
gbdx.s3.delete is too greedy

### ISSUE THREAD

**Issue by drwelby** [DigitalGlobe/gbdxtools#784]
Current behavior doesn't use slash delimiters with the prefix, so `s3.delete('dir')` will match to `dir/`, 'dir_1/`, and anything else starting with `dir*`.

Need to add a slash delimiter and remove code that strips trailing slashes at a minimum.

**Comment by michaelconnor00** [comment]
So the expected behaviour of `s3.delete('dir`)` should match namespaces `dir*`, where `s3.delete('dir/')` should match namespaces `dir/*`? Where currently both would match `dir*`.

**Comment by drwelby** [comment]
Yes, we basically need to implement: https://docs.aws.amazon.com/AmazonS3/latest/dev/ListingKeysHierarchy.html
