### ISSUE TITLE
Python 3.5 doesn't install the latest version of gbdxtools

### ISSUE THREAD

**Issue by mgregor-oa** [DigitalGlobe/gbdxtools#795]
Using conda to create a virtual environment of python version 3.5,
`conda create -n environmentname python=3.5`
then installing gbdxtools using the following after activating you new environment:
`conda install -c conda-forge -c digitalglobe scipy=1.0.0 gbdxtools`
results in gbdxtools 0.15.13 to be installed instead of version 0.16.5 to be installed.
Even if you try to update your version of gbdxtools doing one of the following:
`conda upgrade gbdxtools`
`conda upgrade gbdxtools --update-all`
won't upgrade your gbdxtools version 16.5.  It remains at 15.13.

All tests were performed using 3 different Windows 10 machines.

**Comment by drwelby** [comment]
This is probably due to outdated or unpinned dependencies and should not be a problem with newer releases. Closing for now.
