### ISSUE TITLE
Write function to find all catalog ids that overlap a geometry.

### ISSUE THREAD

**Issue by nricklin** [DigitalGlobe/gbdxtools#8]
_From @kostasthebarbarian on April 2, 2016 0:43_

gbdxtools has no search functionality at the moment. So we need this.

Maybe there has to be a separate search module (search.py) with searching functionality

Look in gbdx.py: there might be some functions in there that do this already.

_Copied from original issue: kostasthebarbarian/gbdxtools#21_

**Comment by kstamatiou** [comment]
At the moment, we have catalog.search_point to find all catalog ids that overlap a point.

**Comment by nricklin** [comment]
#35 adds functionality gbdx.catalog.search()

**Comment by nricklin** [comment]
Also, it allows arbitrarily large searches

**Comment by nricklin** [comment]
gonna call this done.
