### ISSUE TITLE
And centroid option to idaho.get_chip

### ISSUE THREAD

**Issue by loominator1970** [DigitalGlobe/gbdxtools#80]
Currently, the only option for creating a chip is to know the bounding box of the chip you want to create.  It would be useful to have a "centroid" option that allows the user to add the centroid (lat and long) and the max image size in pixels.  This is already an option in the Idaho image service.

**Comment by tpedelose** [comment]
Made a method for this during one of our projects here in Herndon so I figure I might as well send it your way. I don't have access to the repo to make a pull request so I put the code up in a gist: https://gist.github.com/tiranno/8fedcb8e29d47fcd70157ac6ac98336c
