### ISSUE TITLE
Add callbacks to ordering.py

### ISSUE THREAD

**Issue by Mattpwinchester** [DigitalGlobe/gbdxtools#82]
Example of HTTP/JSON: https://gbdxdocs.digitalglobe.com/docs/place-order-with-callbacks

Having the extra functionality in gbdxtools to mimic this request would be ideal. 

Implementation would only require an additional if/else statement with another endpoint designation, correct?

**Comment by nricklin** [comment]
yep looks pretty straightforward to implement

**Comment by amiram** [comment]
@nricklin I think this issue can be closed now.
