### ISSUE TITLE
Ordering heartbeat monitor

### ISSUE THREAD

**Issue by Mattpwinchester** [DigitalGlobe/gbdxtools#83]
Example: https://gbdxdocs.digitalglobe.com/docs/orders-heartbeat-v2

Before I spin up a batch order, I would like to have a function in gbdxtools that I could use to check the status of the ordering API. Currently, I am using a python requests object and I think that checking the API should be part of the toolbox. 

Or should I just create an interface and fire off a dummy order to check the response?

**Comment by nricklin** [comment]
For the most part, the orders API should be assumed to be always up and fine.

However I don't see much downside to having something like 
```python
gbdx.orders.heartbeat()
```
return True of False

**Comment by nricklin** [comment]
v0.9.1 now has ```gbdx.ordering.heartbeat()```
