### ISSUE TITLE
Passing a string that is an encoded json list makes a batch workflow

### ISSUE THREAD

**Issue by nswanson7** [DigitalGlobe/gbdxtools#88]
My task needs a list of inputs, and not have it be broken out as a batch workflow. So I had encoded an input list as a string, but gbdxtools still breaks out the encoded string and makes a batch workflow anyways:

input_list = ['test1','test2','test3']
test_task = gbdx.Task('BBA')
test_task.inputs = json.dumps(input_list)
test_workflow = gbdx.Workflow([test_task])
test_workflow.batch_values
[{'values': ['test1', 'test2', 'test3'], 'name': 'batch_input_oneb_url_list'}]

Note that if you send it a list (not encoded), you get the same result:

input_list = ['test1','test2','test3']
test_task = gbdx.Task('BBA')
test_task.inputs = input_list
test_workflow = gbdx.Workflow([test_task])
test_workflow.batch_values
[{'values': ['test1', 'test2', 'test3'], 'name': 'batch_input_oneb_url_list'}]

**Comment by nricklin** [comment]
Hey @nswanson7, I cannot reproduce.  Can you do a 
```
pip install -U gbdxtools
```
to upgrade to the latest version of gbdxtools?

Also I think you need to do:
```
test_task.inputs.oneb_url_list = json.dumps(input_list)
```

**Comment by nswanson7** [comment]
Upgrading fixed issue, sorry for alarm.

**Comment by nricklin** [comment]
no prob.
