### ISSUE TITLE
retrieving data from idaho api

### ISSUE THREAD

**Issue by garciapablo** [DigitalGlobe/gbdxtools#89]
I'm working on retrieving imagery from the idaho api. I'm having to dig into gbdxtools idaho.py file to gather metadata about the imagery that is being chosen. I have a couple of questions:

1. is there other ways to retrieve an idaho image id metadata?

2. in lines 175-184, it looks like if there are multiple idaho images identified, you will get the last one that qualifies for that criteria and then download that one. I feel like this is an error in the code?

3. How open are you all to other people contributing to this library? We're making a lot of use of this idaho api and it would be nice to have those features  (when an image is downloaded to get the idaho id as well as metadata about the image back). I can implement them with a pull request but want to get your opinion first.

**Comment by chelm** [comment]
Hi, We're very open to pull requests, that would be great. There are some new ways of accessing idaho metadata etc that are currently being tested and should land very soon. Hopefully we can work together via PRs to make sure you're issues are being met.

**Comment by chelm** [comment]
closing. the preferred way to access idaho imagery is now via the CatalogImage or IdahoImage interfaces http://gbdxtools.readthedocs.io/en/latest/image_classes.html
