### ISSUE TITLE
Issues Download from S3

### ISSUE THREAD

**Issue by garciapablo** [DigitalGlobe/gbdxtools#95]
Hello,

I'm attempting to use the download functionality:
```
gbdx.s3.download()
```
When I try to download a directory, it downloads some files but eventually it stops downloading and just gets stuck. I've tried downloading individual files and that also doesn't work.

I'm running a session in iPython, so is something happening with credentials? Is there throttling happening? I'm able to download from the UI.

**Comment by nricklin** [comment]
Our implementation of s3 downloading is not as good as Amazon's own awscli.  

Here's a little script that shows how to do that:
https://github.com/DigitalGlobe/gbdx-s3-creds
